from __future__ import annotations

import io
import re
import sys
import threading
from collections.abc import Iterable
from pathlib import Path

from . import paths
from .errors import DeployError

_TOKEN = re.compile(r"@@([A-Z0-9_]+)@@")

# Guards every import of the vendored NuML codegen packages (mutates `sys.path` and
# `sys.dont_write_bytecode`) and every run of the imported codegen's `code_gen()` (captured by
# temporarily swapping `sys.stdout`). Both operations touch global interpreter state that must
# not be interleaved across threads. JobManager only ever runs one deploy job at a time, but this
# keeps `generate_model_sources()` safe to call from anywhere else too.
_STATE_LOCK = threading.Lock()


def render_tokens(text: str, tokens: dict[str, str]) -> str:
    """Substitute `@@NAME@@` placeholders from `tokens`; any leftover placeholder raises."""
    out = _TOKEN.sub(lambda m: tokens[m.group(1)] if m.group(1) in tokens else m.group(0), text)
    leftover = _TOKEN.search(out)
    if leftover:
        raise DeployError(f"樣板 token 未替換：{leftover.group(0)}")
    return out


def scrub_paths(text: str, pairs: Iterable[tuple[str, str]]) -> str:
    """Rewrite absolute paths in a log before it is written out.

    `build.log` and `numl_codegen.log` both ship to the student (and inside the firmware ZIP),
    where an absolute path leaks the Windows username. The replacements are the same pairs the
    compiler gets through `-ffile-prefix-map` (BSP root -> BSP, app dir -> APP), so a log line
    and the `__FILE__` baked into the firmware name the same thing. Longest prefix first, so a
    nested directory is not half-rewritten by its own parent.
    """
    for old, new in sorted(pairs, key=lambda pair: len(pair[0]), reverse=True):
        if old:
            text = text.replace(str(old), str(new))
    return text


def cpp_escape(value: str) -> str:
    """Escape a Python string for embedding inside a C++ double-quoted string literal.

    Backslash/quote/CR/LF/tab get their usual short escapes; every other control character
    (0x00-0x1f, 0x7f) is escaped as a fixed-width 3-digit octal `\\ooo` rather than `\\xNN` --
    C's hex escape is greedy and would swallow any following hex-digit characters into the same
    escape sequence.
    """
    out: list[str] = []
    for ch in str(value):
        if ch == "\\":
            out.append("\\\\")
        elif ch == '"':
            out.append('\\"')
        elif ch == "\n":
            out.append("\\n")
        elif ch == "\r":
            out.append("\\r")
        elif ch == "\t":
            out.append("\\t")
        elif ord(ch) < 0x20 or ord(ch) == 0x7F:
            out.append(f"\\{ord(ch):03o}")
        else:
            out.append(ch)
    return "".join(out)


def activation_define(arena_bytes: int) -> str:
    return f"#define ACTIVATION_BUF_SZ ({int(arena_bytes)})"


def model_cpp_text(model_bytes: bytes) -> str:
    """Render `Model.cpp`: the model byte array plus the accessor functions the firmware calls."""
    if not model_bytes:
        raise DeployError("模型是空的（0 bytes），無法產生 Model.cpp；請確認 Vela 是否正確輸出模型檔")
    lines = [
        "/* Auto-generated by Teachable Machine Local Studio (mcu deploy). Do not edit. */",
        "",
        '#include "Model.hpp"',
        '#include "BufAttributes.hpp"',
        "",
        "namespace arm {",
        "namespace app {",
        "namespace nn {",
        "",
        "static const uint8_t nn_model[] MODEL_TFLITE_ATTRIBUTE =",
        "{",
    ]
    for offset in range(0, len(model_bytes), 16):
        chunk = model_bytes[offset : offset + 16]
        lines.append("    " + ", ".join(f"0x{b:02x}" for b in chunk) + ",")
    lines += [
        "};",
        "",
        "const uint8_t * GetModelPointer()",
        "{",
        "    return nn_model;",
        "}",
        "",
        "size_t GetModelLen()",
        "{",
        "    return sizeof(nn_model);",
        "}",
        "",
        "} /* namespace nn */",
        "} /* namespace app */",
        "} /* namespace arm */",
        "",
    ]
    return "\n".join(lines)


def write_model_cpp(model_bytes: bytes, out_path: Path) -> None:
    out_path = Path(out_path)
    out_path.parent.mkdir(parents=True, exist_ok=True)
    out_path.write_text(model_cpp_text(model_bytes), encoding="utf-8", newline="\n")


def labels_hpp_text() -> str:
    return (
        "/* Auto-generated by Teachable Machine Local Studio (mcu deploy). Do not edit. */\n"
        "#ifndef LABELS_HPP\n#define LABELS_HPP\n\n"
        "#include <stddef.h>\n#include <string>\n#include <vector>\n\n"
        "extern size_t GetLabelCount(void);\n"
        "extern const char *GetLabelByIndex(size_t index);\n"
        "extern bool GetLabelsVector(std::vector<std::string> &labels);\n\n"
        "#endif /* LABELS_HPP */\n"
    )


def labels_cpp_text(labels: list[str]) -> str:
    if not labels:
        raise DeployError("類別清單是空的，無法產生 Labels.cpp")
    entries = "\n".join(f'    "{cpp_escape(label)}",' for label in labels)
    return (
        "/* Auto-generated by Teachable Machine Local Studio (mcu deploy). Do not edit. */\n"
        '#include "BufAttributes.hpp"\n#include "Labels.hpp"\n#include <stddef.h>\n'
        "#include <string>\n#include <vector>\n\n"
        "static const char *labelsVec[] LABELS_ATTRIBUTE =\n{\n"
        f"{entries}\n"
        "};\n\n"
        "size_t GetLabelCount(void)\n{\n    return sizeof(labelsVec) / sizeof(labelsVec[0]);\n}\n\n"
        "const char *GetLabelByIndex(size_t index)\n{\n"
        '    return (index < GetLabelCount()) ? labelsVec[index] : "???";\n}\n\n'
        "bool GetLabelsVector(std::vector<std::string> &labels)\n{\n"
        "    constexpr size_t labelsSz = sizeof(labelsVec) / sizeof(labelsVec[0]);\n"
        "    labels.clear();\n    labels.reserve(labelsSz);\n"
        "    for (size_t i = 0; i < labelsSz; ++i)\n    {\n        labels.emplace_back(labelsVec[i]);\n    }\n"
        "    return labelsSz > 0;\n}\n"
    )


def write_labels(labels: list[str], model_dir: Path) -> None:
    include_dir = Path(model_dir) / "include"
    include_dir.mkdir(parents=True, exist_ok=True)
    (include_dir / "Labels.hpp").write_text(labels_hpp_text(), encoding="utf-8", newline="\n")
    (Path(model_dir) / "Labels.cpp").write_text(
        labels_cpp_text(labels), encoding="utf-8", newline="\n"
    )


def _import_numl_codegen(application: str):
    """Import the vendored NuML codegen class.

    Puts `NUML_ROOT` on `sys.path` lazily -- appended, never inserted at index 0, because
    `NUML_ROOT` ships its own top-level `tflite`/`templates` packages that must not shadow
    anything already resolvable from site-packages or the app for the rest of the process's
    life -- and disables bytecode caching for the import (guarded by `_STATE_LOCK`, since the
    save/restore of `sys.dont_write_bytecode` is otherwise not reentrant across threads) so it
    never leaves `__pycache__` directories inside the vendored, checksummed `mcu_toolkit/` tree.
    Never imports NuML's own `project_generate` / `numl_tool` CLI entry point scripts -- only the
    two codegen packages this module bridges to.
    """
    with _STATE_LOCK:
        if str(paths.NUML_ROOT) not in sys.path:
            sys.path.append(str(paths.NUML_ROOT))
        previous = sys.dont_write_bytecode
        sys.dont_write_bytecode = True
        try:
            if application == "imgclass":
                from imgclass_codegen.imgclass_codegen import ImgClassCodegen as Codegen
            else:
                from generic_codegen.generic_codegen import GenericCodegen as Codegen
        finally:
            sys.dont_write_bytecode = previous
    return Codegen


class _TeeStdout:
    """Writes to both the real stdout and an in-memory buffer.

    Used instead of `contextlib.redirect_stdout` while running the vendored NuML codegen: that
    context manager would fully displace `sys.stdout` (e.g. the session's own `TeeTextIO` log
    stream) for the duration of the call and swallow anything other threads print in the
    meantime. Tee-ing keeps the real stream live for everyone else while we also capture NuML's
    own `print()` diagnostics for the error message / log file.
    """

    def __init__(self, original, buffer: io.StringIO) -> None:
        self._original = original
        self._buffer = buffer

    def write(self, text: str) -> int:
        self._buffer.write(text)
        return self._original.write(text)

    def flush(self) -> None:
        self._original.flush()

    def __getattr__(self, name: str):
        return getattr(self._original, name)


def _expected_model_outputs(application: str) -> tuple[str, str]:
    """Relative `(hpp, cpp)` paths NuML's codegen must produce for `application`."""
    if application == "imgclass":
        return "Model/include/MobileNetModel.hpp", "Model/MobileNetModel.cpp"
    return "Model/include/NNModel.hpp", "Model/NNModel.cpp"


def generate_model_sources(
    application: str, vela_tflite: Path, app_dir: Path, summary_csv: Path
) -> None:
    """Run the vendored NuML codegen to produce `Model/include/{MobileNetModel|NNModel}.hpp`
    and `Model/{MobileNetModel|NNModel}.cpp`, plus NuML's own `main.cpp` (callers must overwrite
    with the real `main.cpp.in` rendering via `render_tokens()`).

    Label files differ by application: on `imgclass`, NuML also writes a numeric-placeholder
    `Model/Labels.cpp` that callers must overwrite with `write_labels()`; every other application
    gets no `Labels.cpp`/`Labels.hpp` from NuML at all, so callers must call `write_labels()` to
    CREATE both files from scratch.

    Every failure -- an exception raised anywhere in the vendored call tree (unsupported opcode,
    a malformed Vela summary, a missing jinja2 template, ...), NuML's own `"unable_generate"`
    return, or a successful-looking return that did not actually produce the expected
    `.hpp`/`.cpp` pair -- is surfaced as a `DeployError` (Traditional Chinese) naming the
    application and the last lines of the codegen's own stdout. That stdout is also written in
    full to `<app_dir>/numl_codegen.log` (LF newlines) on both success and failure.
    """
    app_dir = Path(app_dir)
    (app_dir / "Model" / "include").mkdir(parents=True, exist_ok=True)
    hpp_rel, cpp_rel = _expected_model_outputs(application)
    Codegen = _import_numl_codegen(application)

    error: Exception | None = None
    outcome = None
    with _STATE_LOCK:
        original_stdout = sys.stdout
        buffer = io.StringIO()
        sys.stdout = _TeeStdout(original_stdout, buffer)
        try:
            gen = Codegen.from_args(
                str(vela_tflite), str(app_dir), str(summary_csv), app=application
            )
            outcome = gen.code_gen()
        except Exception as exc:  # noqa: BLE001 - every vendored-codegen failure becomes a DeployError
            error = exc
        finally:
            sys.stdout = original_stdout
        captured = buffer.getvalue()

    # The vendored codegen prints absolute paths: its own tree, the app dir, and (via the Vela
    # model path it is handed) the caller's work dir under MCU_TEMP_ROOT. Scrub all three before
    # the log is written *and* before the tail -- or the raw exception text -- goes into any
    # DeployError the student reads: all of these travel off this machine inside the firmware
    # ZIP / a diagnostics paste.
    scrub_pairs = [
        (str(app_dir), "APP"),
        (str(paths.NUML_ROOT), "NUML"),
        (str(paths.MCU_TEMP_ROOT), "TMP"),
    ]
    captured = scrub_paths(captured, scrub_pairs)
    (app_dir / "numl_codegen.log").write_text(captured, encoding="utf-8", newline="\n")
    tail = captured[-2000:]

    if error is not None:
        scrubbed_error = scrub_paths(str(error), scrub_pairs)
        raise DeployError(
            f"韌體模型程式碼產生失敗（{application}）：{scrubbed_error}\n{tail}"
        ) from error
    if outcome == "unable_generate":
        raise DeployError(f"韌體模型程式碼產生失敗（{application}）：\n{tail}")
    hpp_path = app_dir / hpp_rel
    cpp_path = app_dir / cpp_rel
    if not hpp_path.is_file() or not cpp_path.is_file():
        raise DeployError(
            f"韌體模型程式碼產生失敗（{application}）：缺少預期輸出 {hpp_rel} 或 {cpp_rel}\n{tail}"
        )
