/**************************************************************************//**
 * @file     numl_usbd.h
 * @brief    HSUSB CDC virtual COM port for a NuML project with no video function.
 *
 * Generated by NuML Application Builder v0.1.8 -- do not edit by hand.
 * Every Generate and Build re-applies this file.
 * NUML_APP_BUILDER_USB_CDC_DEVICE_V0_1_8
 ******************************************************************************/
#ifndef __NUML_USBD_H__
#define __NUML_USBD_H__

#ifdef __cplusplus
extern "C" {
#endif

/* Brings up the HSUSB PHY, opens HSUSBD and enables the CDC endpoints.
 * Safe to call once, before the inference loop starts. */
void NuML_USBD_Init(void);

#ifdef __cplusplus
}
#endif

#endif  /* __NUML_USBD_H__ */
