/**************************************************************************//**
 * @file     numl_usbd.c
 * @brief    CDC-only HSUSB device: descriptors, bring-up and interrupt handler.
 *
 * Generated by NuML Application Builder v0.1.8 -- do not edit by hand.
 * Every Generate and Build re-applies this file.
 * NUML_APP_BUILDER_USB_CDC_DEVICE_V0_1_8
 ******************************************************************************/

/* CDC-only HSUSB device for a NuML project that has no video function.
 *
 * The interrupt handler is deliberately the same shape as the UVC template's
 * HSUSBD_IRQHandler with the ISO/video paths removed, so the control-endpoint
 * state machine stays byte-for-byte the sequence Nuvoton ships and has tested.
 */

#include <stdint.h>
#include "NuMicro.h"
#include "numl_cdc.h"
#include "numl_usbd.h"

/* NUML_APP_BUILDER_USB_CDC_DEVICE_V0_1_8 */

/*----------------------------------------------------------------------------
 * Descriptors
 *--------------------------------------------------------------------------*/

const uint8_t gu8NuMLDeviceDescriptor[] =
{
    0x12,       /* bLength */
    0x01,       /* bDescriptorType: DEVICE */
    0x00, 0x02, /* bcdUSB: 2.00 */
    0xEF,       /* bDeviceClass: miscellaneous */
    0x02,       /* bDeviceSubClass: common class */
    0x01,       /* bDeviceProtocol: interface association */
    0x40,       /* bMaxPacketSize0: 64 */
    0x16, 0x04, /* idVendor */
    0x05, 0x11, /* idProduct */
    0x00, 0x03, /* bcdDevice */
    0x01,       /* iManufacturer */
    0x02,       /* iProduct */
    0x03,       /* iSerialNumber */
    0x01        /* bNumConfigurations */
};

const uint8_t gu8NuMLQualifierDescriptor[] =
{
    0x0A,       /* bLength */
    0x06,       /* bDescriptorType: DEVICE QUALIFIER */
    0x00, 0x02, /* bcdUSB: 2.00 */
    0xEF,       /* bDeviceClass */
    0x02,       /* bDeviceSubClass */
    0x01,       /* bDeviceProtocol */
    0x40,       /* bMaxPacketSize0 */
    0x01,       /* bNumConfigurations */
    0x00        /* bReserved */
};

/* configuration, high speed */
const uint8_t gu8NuMLConfigDescriptor[] =
{
    0x09,       /* bLength */
    0x02,       /* bDescriptorType */
    0x4B, 0x00, /* wTotalLength: 75 */
    0x02,       /* bNumInterfaces */
    0x01,       /* bConfigurationValue */
    0x00,       /* iConfiguration */
    0x80,       /* bmAttributes: bus powered */
    0xFA,       /* bMaxPower: 500 mA */

    /* ==== NUML_APP_BUILDER_USB_CDC_RUNTIME_V0_1_8 (high speed) ====================== */
    /* CDC ACM function: interface association */
    0x08,       /* bLength */
    0x0B,       /* bDescriptorType: IAD */
    0x00,       /* bFirstInterface */
    0x02,       /* bInterfaceCount */
    0x02,       /* bFunctionClass: CDC */
    0x02,       /* bFunctionSubClass: Abstract Control Model */
    0x01,       /* bFunctionProtocol: AT commands */
    0x00,       /* iFunction */

    /* CDC communication interface */
    0x09,       /* bLength */
    0x04,       /* bDescriptorType: INTERFACE */
    0x00,       /* bInterfaceNumber */
    0x00,       /* bAlternateSetting */
    0x01,       /* bNumEndpoints */
    0x02,       /* bInterfaceClass: CDC */
    0x02,       /* bInterfaceSubClass: ACM */
    0x01,       /* bInterfaceProtocol: AT commands */
    0x00,       /* iInterface */

    /* CDC header functional descriptor */
    0x05, 0x24, 0x00, 0x10, 0x01,

    /* CDC call management functional descriptor */
    0x05, 0x24, 0x01, 0x00, 0x01,

    /* CDC abstract control management functional descriptor */
    0x04, 0x24, 0x02, 0x02,

    /* CDC union functional descriptor */
    0x05, 0x24, 0x06, 0x00, 0x01,

    /* Notification endpoint (EP5 IN, interrupt) */
    0x07,       /* bLength */
    0x05,       /* bDescriptorType: ENDPOINT */
    0x85,       /* bEndpointAddress: IN 5 */
    0x03,       /* bmAttributes: interrupt */
    0x10, 0x00, /* wMaxPacketSize: 16 */
    0x09,       /* bInterval */

    /* CDC data interface */
    0x09,       /* bLength */
    0x04,       /* bDescriptorType: INTERFACE */
    0x01,       /* bInterfaceNumber */
    0x00,       /* bAlternateSetting */
    0x02,       /* bNumEndpoints */
    0x0A,       /* bInterfaceClass: CDC data */
    0x00,       /* bInterfaceSubClass */
    0x00,       /* bInterfaceProtocol */
    0x00,       /* iInterface */

    /* Bulk OUT endpoint (EP4 OUT) */
    0x07, 0x05, 0x04, 0x02, 0x00, 0x02, 0x00,

    /* Bulk IN endpoint (EP2 IN) */
    0x07, 0x05, 0x82, 0x02, 0x00, 0x02, 0x00,
    /* ==== end NUML_APP_BUILDER_USB_CDC_RUNTIME_V0_1_8 ========================== */
};

/* configuration, full speed */
const uint8_t gu8NuMLConfigDescriptorFS[] =
{
    0x09,       /* bLength */
    0x02,       /* bDescriptorType */
    0x4B, 0x00, /* wTotalLength: 75 */
    0x02,       /* bNumInterfaces */
    0x01,       /* bConfigurationValue */
    0x00,       /* iConfiguration */
    0x80,       /* bmAttributes: bus powered */
    0xFA,       /* bMaxPower: 500 mA */

    /* ==== NUML_APP_BUILDER_USB_CDC_RUNTIME_V0_1_8 (full speed) ====================== */
    /* CDC ACM function: interface association */
    0x08,       /* bLength */
    0x0B,       /* bDescriptorType: IAD */
    0x00,       /* bFirstInterface */
    0x02,       /* bInterfaceCount */
    0x02,       /* bFunctionClass: CDC */
    0x02,       /* bFunctionSubClass: Abstract Control Model */
    0x01,       /* bFunctionProtocol: AT commands */
    0x00,       /* iFunction */

    /* CDC communication interface */
    0x09,       /* bLength */
    0x04,       /* bDescriptorType: INTERFACE */
    0x00,       /* bInterfaceNumber */
    0x00,       /* bAlternateSetting */
    0x01,       /* bNumEndpoints */
    0x02,       /* bInterfaceClass: CDC */
    0x02,       /* bInterfaceSubClass: ACM */
    0x01,       /* bInterfaceProtocol: AT commands */
    0x00,       /* iInterface */

    /* CDC header functional descriptor */
    0x05, 0x24, 0x00, 0x10, 0x01,

    /* CDC call management functional descriptor */
    0x05, 0x24, 0x01, 0x00, 0x01,

    /* CDC abstract control management functional descriptor */
    0x04, 0x24, 0x02, 0x02,

    /* CDC union functional descriptor */
    0x05, 0x24, 0x06, 0x00, 0x01,

    /* Notification endpoint (EP5 IN, interrupt) */
    0x07,       /* bLength */
    0x05,       /* bDescriptorType: ENDPOINT */
    0x85,       /* bEndpointAddress: IN 5 */
    0x03,       /* bmAttributes: interrupt */
    0x10, 0x00, /* wMaxPacketSize: 16 */
    0xFF,       /* bInterval */

    /* CDC data interface */
    0x09,       /* bLength */
    0x04,       /* bDescriptorType: INTERFACE */
    0x01,       /* bInterfaceNumber */
    0x00,       /* bAlternateSetting */
    0x02,       /* bNumEndpoints */
    0x0A,       /* bInterfaceClass: CDC data */
    0x00,       /* bInterfaceSubClass */
    0x00,       /* bInterfaceProtocol */
    0x00,       /* iInterface */

    /* Bulk OUT endpoint (EP4 OUT) */
    0x07, 0x05, 0x04, 0x02, 0x40, 0x00, 0x00,

    /* Bulk IN endpoint (EP2 IN) */
    0x07, 0x05, 0x82, 0x02, 0x40, 0x00, 0x00,
    /* ==== end NUML_APP_BUILDER_USB_CDC_RUNTIME_V0_1_8 ========================== */
};

/* other-speed configuration, full speed */
const uint8_t gu8NuMLOtherConfigDescriptorHS[] =
{
    0x09,       /* bLength */
    0x07,       /* bDescriptorType */
    0x4B, 0x00, /* wTotalLength: 75 */
    0x02,       /* bNumInterfaces */
    0x01,       /* bConfigurationValue */
    0x00,       /* iConfiguration */
    0x80,       /* bmAttributes: bus powered */
    0xFA,       /* bMaxPower: 500 mA */

    /* ==== NUML_APP_BUILDER_USB_CDC_RUNTIME_V0_1_8 (full speed) ====================== */
    /* CDC ACM function: interface association */
    0x08,       /* bLength */
    0x0B,       /* bDescriptorType: IAD */
    0x00,       /* bFirstInterface */
    0x02,       /* bInterfaceCount */
    0x02,       /* bFunctionClass: CDC */
    0x02,       /* bFunctionSubClass: Abstract Control Model */
    0x01,       /* bFunctionProtocol: AT commands */
    0x00,       /* iFunction */

    /* CDC communication interface */
    0x09,       /* bLength */
    0x04,       /* bDescriptorType: INTERFACE */
    0x00,       /* bInterfaceNumber */
    0x00,       /* bAlternateSetting */
    0x01,       /* bNumEndpoints */
    0x02,       /* bInterfaceClass: CDC */
    0x02,       /* bInterfaceSubClass: ACM */
    0x01,       /* bInterfaceProtocol: AT commands */
    0x00,       /* iInterface */

    /* CDC header functional descriptor */
    0x05, 0x24, 0x00, 0x10, 0x01,

    /* CDC call management functional descriptor */
    0x05, 0x24, 0x01, 0x00, 0x01,

    /* CDC abstract control management functional descriptor */
    0x04, 0x24, 0x02, 0x02,

    /* CDC union functional descriptor */
    0x05, 0x24, 0x06, 0x00, 0x01,

    /* Notification endpoint (EP5 IN, interrupt) */
    0x07,       /* bLength */
    0x05,       /* bDescriptorType: ENDPOINT */
    0x85,       /* bEndpointAddress: IN 5 */
    0x03,       /* bmAttributes: interrupt */
    0x10, 0x00, /* wMaxPacketSize: 16 */
    0xFF,       /* bInterval */

    /* CDC data interface */
    0x09,       /* bLength */
    0x04,       /* bDescriptorType: INTERFACE */
    0x01,       /* bInterfaceNumber */
    0x00,       /* bAlternateSetting */
    0x02,       /* bNumEndpoints */
    0x0A,       /* bInterfaceClass: CDC data */
    0x00,       /* bInterfaceSubClass */
    0x00,       /* bInterfaceProtocol */
    0x00,       /* iInterface */

    /* Bulk OUT endpoint (EP4 OUT) */
    0x07, 0x05, 0x04, 0x02, 0x40, 0x00, 0x00,

    /* Bulk IN endpoint (EP2 IN) */
    0x07, 0x05, 0x82, 0x02, 0x40, 0x00, 0x00,
    /* ==== end NUML_APP_BUILDER_USB_CDC_RUNTIME_V0_1_8 ========================== */
};

/* other-speed configuration, high speed */
const uint8_t gu8NuMLOtherConfigDescriptorFS[] =
{
    0x09,       /* bLength */
    0x07,       /* bDescriptorType */
    0x4B, 0x00, /* wTotalLength: 75 */
    0x02,       /* bNumInterfaces */
    0x01,       /* bConfigurationValue */
    0x00,       /* iConfiguration */
    0x80,       /* bmAttributes: bus powered */
    0xFA,       /* bMaxPower: 500 mA */

    /* ==== NUML_APP_BUILDER_USB_CDC_RUNTIME_V0_1_8 (high speed) ====================== */
    /* CDC ACM function: interface association */
    0x08,       /* bLength */
    0x0B,       /* bDescriptorType: IAD */
    0x00,       /* bFirstInterface */
    0x02,       /* bInterfaceCount */
    0x02,       /* bFunctionClass: CDC */
    0x02,       /* bFunctionSubClass: Abstract Control Model */
    0x01,       /* bFunctionProtocol: AT commands */
    0x00,       /* iFunction */

    /* CDC communication interface */
    0x09,       /* bLength */
    0x04,       /* bDescriptorType: INTERFACE */
    0x00,       /* bInterfaceNumber */
    0x00,       /* bAlternateSetting */
    0x01,       /* bNumEndpoints */
    0x02,       /* bInterfaceClass: CDC */
    0x02,       /* bInterfaceSubClass: ACM */
    0x01,       /* bInterfaceProtocol: AT commands */
    0x00,       /* iInterface */

    /* CDC header functional descriptor */
    0x05, 0x24, 0x00, 0x10, 0x01,

    /* CDC call management functional descriptor */
    0x05, 0x24, 0x01, 0x00, 0x01,

    /* CDC abstract control management functional descriptor */
    0x04, 0x24, 0x02, 0x02,

    /* CDC union functional descriptor */
    0x05, 0x24, 0x06, 0x00, 0x01,

    /* Notification endpoint (EP5 IN, interrupt) */
    0x07,       /* bLength */
    0x05,       /* bDescriptorType: ENDPOINT */
    0x85,       /* bEndpointAddress: IN 5 */
    0x03,       /* bmAttributes: interrupt */
    0x10, 0x00, /* wMaxPacketSize: 16 */
    0x09,       /* bInterval */

    /* CDC data interface */
    0x09,       /* bLength */
    0x04,       /* bDescriptorType: INTERFACE */
    0x01,       /* bInterfaceNumber */
    0x00,       /* bAlternateSetting */
    0x02,       /* bNumEndpoints */
    0x0A,       /* bInterfaceClass: CDC data */
    0x00,       /* bInterfaceSubClass */
    0x00,       /* bInterfaceProtocol */
    0x00,       /* iInterface */

    /* Bulk OUT endpoint (EP4 OUT) */
    0x07, 0x05, 0x04, 0x02, 0x00, 0x02, 0x00,

    /* Bulk IN endpoint (EP2 IN) */
    0x07, 0x05, 0x82, 0x02, 0x00, 0x02, 0x00,
    /* ==== end NUML_APP_BUILDER_USB_CDC_RUNTIME_V0_1_8 ========================== */
};


const uint8_t gu8NuMLStringLang[] =
{
    4, 0x03, 0x09, 0x04
};

const uint8_t gu8NuMLVendorString[] =
{
    16, 0x03, 'N', 0, 'u', 0, 'v', 0, 'o', 0, 't', 0, 'o', 0, 'n', 0
};

const uint8_t gu8NuMLProductString[] =
{
    28, 0x03,
    'N', 0, 'u', 0, 'M', 0, 'L', 0, ' ', 0,
    'V', 0, 'C', 0, 'O', 0, 'M', 0,
    ' ', 0, 'K', 0, 'W', 0, 'S', 0
};

const uint8_t gu8NuMLStringSerial[] =
{
    26, 0x03,
    'N', 0, 'u', 0, 'M', 0, 'L', 0, '0', 0, '1', 0,
    '0', 0, '0', 0, '0', 0, '0', 0, '1', 0, '8', 0
};

const uint8_t *gpu8NuMLUsbString[4] =
{
    gu8NuMLStringLang,
    gu8NuMLVendorString,
    gu8NuMLProductString,
    gu8NuMLStringSerial
};

S_HSUSBD_INFO_T gsNuMLHSInfo =
{
    (uint8_t *)gu8NuMLDeviceDescriptor,
    (uint8_t *)gu8NuMLConfigDescriptor,
    (uint8_t **)gpu8NuMLUsbString,
    (uint8_t *)gu8NuMLQualifierDescriptor,
    (uint8_t *)gu8NuMLConfigDescriptorFS,
    (uint8_t *)gu8NuMLOtherConfigDescriptorHS,
    (uint8_t *)gu8NuMLOtherConfigDescriptorFS,
    NULL,
    NULL,
    NULL,
    NULL
};

/*----------------------------------------------------------------------------
 * Class requests
 *--------------------------------------------------------------------------*/

static void NuML_USBD_ClassRequest(void)
{
    if (NuML_CDC_ClassRequest())
    {
        return;
    }

    /* Not ours: stall the control endpoint. */
    HSUSBD_SetStall(0);
}

static void NuML_USBD_SetInterface(uint32_t u32AltInterface)
{
    /* The CDC function has no alternate settings. */
    (void)u32AltInterface;
}

/*----------------------------------------------------------------------------
 * Interrupt handler
 *--------------------------------------------------------------------------*/

void HSUSBD_IRQHandler(void)
{
    volatile uint32_t IrqStL, IrqSt;
    uint32_t u32TimeOutCnt;

    IrqStL = HSUSBD->GINTSTS & HSUSBD->GINTEN;

    if (!IrqStL) return;

    if (IrqStL & HSUSBD_GINTSTS_USBIF_Msk)
    {
        IrqSt = HSUSBD->BUSINTSTS & HSUSBD->BUSINTEN;

        if (IrqSt & HSUSBD_BUSINTSTS_SOFIF_Msk)
            HSUSBD_CLR_BUS_INT_FLAG(HSUSBD_BUSINTSTS_SOFIF_Msk);

        if (IrqSt & HSUSBD_BUSINTSTS_RSTIF_Msk)
        {
            HSUSBD_SwReset();
            NuML_CDC_Reset();

            HSUSBD_ResetDMA();
            HSUSBD->EP[EPB].EPRSPCTL = HSUSBD_EPRSPCTL_FLUSH_Msk;
            HSUSBD->EP[EPD].EPRSPCTL = HSUSBD_EPRSPCTL_FLUSH_Msk;

            if (HSUSBD->OPER & 0x04)     /* high speed */
                NuML_CDC_InitForHighSpeed();
            else                         /* full speed */
                NuML_CDC_InitForFullSpeed();

            HSUSBD_ENABLE_CEP_INT(HSUSBD_CEPINTEN_SETUPPKIEN_Msk);
            HSUSBD_SET_ADDR(0);
            HSUSBD_ENABLE_BUS_INT(HSUSBD_BUSINTEN_RSTIEN_Msk | HSUSBD_BUSINTEN_RESUMEIEN_Msk | HSUSBD_BUSINTEN_SUSPENDIEN_Msk);
            HSUSBD_CLR_BUS_INT_FLAG(HSUSBD_BUSINTSTS_RSTIF_Msk);
            HSUSBD_CLR_CEP_INT_FLAG(0x1ffc);
        }

        if (IrqSt & HSUSBD_BUSINTSTS_RESUMEIF_Msk)
        {
            HSUSBD_ENABLE_BUS_INT(HSUSBD_BUSINTEN_RSTIEN_Msk | HSUSBD_BUSINTEN_SUSPENDIEN_Msk);
            HSUSBD_CLR_BUS_INT_FLAG(HSUSBD_BUSINTSTS_RESUMEIF_Msk);
        }

        if (IrqSt & HSUSBD_BUSINTSTS_SUSPENDIF_Msk)
        {
            HSUSBD_ENABLE_BUS_INT(HSUSBD_BUSINTEN_RSTIEN_Msk | HSUSBD_BUSINTEN_RESUMEIEN_Msk);
            HSUSBD_CLR_BUS_INT_FLAG(HSUSBD_BUSINTSTS_SUSPENDIF_Msk);
        }

        if (IrqSt & HSUSBD_BUSINTSTS_HISPDIF_Msk)
        {
            HSUSBD_ENABLE_CEP_INT(HSUSBD_CEPINTEN_SETUPPKIEN_Msk);
            HSUSBD_CLR_BUS_INT_FLAG(HSUSBD_BUSINTSTS_HISPDIF_Msk);
        }

        if (IrqSt & HSUSBD_BUSINTSTS_DMADONEIF_Msk)
        {
            /* Nothing here uses the DMA engine; keep the flag consistent for
             * the BSP driver and clear the interrupt. */
            g_hsusbd_DmaDone = 1;
            HSUSBD_CLR_BUS_INT_FLAG(HSUSBD_BUSINTSTS_DMADONEIF_Msk);
        }

        if (IrqSt & HSUSBD_BUSINTSTS_PHYCLKVLDIF_Msk)
            HSUSBD_CLR_BUS_INT_FLAG(HSUSBD_BUSINTSTS_PHYCLKVLDIF_Msk);

        if (IrqSt & HSUSBD_BUSINTSTS_VBUSDETIF_Msk)
        {
            if (HSUSBD_IS_ATTACHED())
            {
                HSUSBD_ENABLE_USB();
                u32TimeOutCnt = SystemCoreClock;    /* 1 second time-out */

                while (!(HSUSBD->PHYCTL & HSUSBD_PHYCTL_PHYCLKSTB_Msk))
                    if (--u32TimeOutCnt == 0) break;
            }
            else
            {
                NuML_CDC_Reset();
                HSUSBD_DISABLE_USB();
                HSUSBD->OPER &= ~HSUSBD_OPER_HISHSEN_Msk;
            }

            HSUSBD_CLR_BUS_INT_FLAG(HSUSBD_BUSINTSTS_VBUSDETIF_Msk);
        }
    }

    if (IrqStL & HSUSBD_GINTSTS_CEPIF_Msk)
    {
        IrqSt = HSUSBD->CEPINTSTS & HSUSBD->CEPINTEN;

        if (IrqSt & HSUSBD_CEPINTSTS_SETUPTKIF_Msk)
        {
            HSUSBD_CLR_CEP_INT_FLAG(HSUSBD_CEPINTSTS_SETUPTKIF_Msk);
            goto exit_HSUSBD_IRQHandler;
        }

        if (IrqSt & HSUSBD_CEPINTSTS_SETUPPKIF_Msk)
        {
            HSUSBD_CLR_CEP_INT_FLAG(HSUSBD_CEPINTSTS_SETUPPKIF_Msk);
            HSUSBD_ProcessSetupPacket();
            goto exit_HSUSBD_IRQHandler;
        }

        if (IrqSt & HSUSBD_CEPINTSTS_OUTTKIF_Msk)
        {
            HSUSBD_CLR_CEP_INT_FLAG(HSUSBD_CEPINTSTS_OUTTKIF_Msk);
            HSUSBD_ENABLE_CEP_INT(HSUSBD_CEPINTEN_STSDONEIEN_Msk);
            goto exit_HSUSBD_IRQHandler;
        }

        if (IrqSt & HSUSBD_CEPINTSTS_INTKIF_Msk)
        {
            HSUSBD_CLR_CEP_INT_FLAG(HSUSBD_CEPINTSTS_INTKIF_Msk);

            if (!(IrqSt & HSUSBD_CEPINTSTS_STSDONEIF_Msk))
            {
                HSUSBD_CLR_CEP_INT_FLAG(HSUSBD_CEPINTSTS_TXPKIF_Msk);
                HSUSBD_ENABLE_CEP_INT(HSUSBD_CEPINTEN_TXPKIEN_Msk);
                HSUSBD_CtrlIn();
            }
            else
            {
                HSUSBD_CLR_CEP_INT_FLAG(HSUSBD_CEPINTSTS_TXPKIF_Msk);
                HSUSBD_ENABLE_CEP_INT(HSUSBD_CEPINTEN_TXPKIEN_Msk | HSUSBD_CEPINTEN_STSDONEIEN_Msk);
            }

            goto exit_HSUSBD_IRQHandler;
        }

        if (IrqSt & HSUSBD_CEPINTSTS_PINGIF_Msk)
        {
            HSUSBD_CLR_CEP_INT_FLAG(HSUSBD_CEPINTSTS_PINGIF_Msk);
            goto exit_HSUSBD_IRQHandler;
        }

        if (IrqSt & HSUSBD_CEPINTSTS_TXPKIF_Msk)
        {
            HSUSBD_CLR_CEP_INT_FLAG(HSUSBD_CEPINTSTS_STSDONEIF_Msk);
            HSUSBD_SET_CEP_STATE(HSUSBD_CEPCTL_NAKCLR);

            if (g_hsusbd_CtrlInSize)
            {
                HSUSBD_CLR_CEP_INT_FLAG(HSUSBD_CEPINTSTS_INTKIF_Msk);
                HSUSBD_ENABLE_CEP_INT(HSUSBD_CEPINTEN_INTKIEN_Msk);
            }
            else
            {
                if (g_hsusbd_CtrlZero == 1)
                    HSUSBD_SET_CEP_STATE(HSUSBD_CEPCTL_ZEROLEN);

                HSUSBD_CLR_CEP_INT_FLAG(HSUSBD_CEPINTSTS_STSDONEIF_Msk);
                HSUSBD_ENABLE_CEP_INT(HSUSBD_CEPINTEN_SETUPPKIEN_Msk | HSUSBD_CEPINTEN_STSDONEIEN_Msk);
            }

            HSUSBD_CLR_CEP_INT_FLAG(HSUSBD_CEPINTSTS_TXPKIF_Msk);
            goto exit_HSUSBD_IRQHandler;
        }

        if (IrqSt & HSUSBD_CEPINTSTS_RXPKIF_Msk)
        {
            HSUSBD_CLR_CEP_INT_FLAG(HSUSBD_CEPINTSTS_RXPKIF_Msk);
            HSUSBD_SET_CEP_STATE(HSUSBD_CEPCTL_NAKCLR);
            HSUSBD_ENABLE_CEP_INT(HSUSBD_CEPINTEN_SETUPPKIEN_Msk | HSUSBD_CEPINTEN_STSDONEIEN_Msk);
            goto exit_HSUSBD_IRQHandler;
        }

        if (IrqSt & HSUSBD_CEPINTSTS_NAKIF_Msk)
        {
            HSUSBD_CLR_CEP_INT_FLAG(HSUSBD_CEPINTSTS_NAKIF_Msk);
            goto exit_HSUSBD_IRQHandler;
        }

        if (IrqSt & HSUSBD_CEPINTSTS_STALLIF_Msk)
        {
            HSUSBD_CLR_CEP_INT_FLAG(HSUSBD_CEPINTSTS_STALLIF_Msk);
            goto exit_HSUSBD_IRQHandler;
        }

        if (IrqSt & HSUSBD_CEPINTSTS_ERRIF_Msk)
        {
            HSUSBD_CLR_CEP_INT_FLAG(HSUSBD_CEPINTSTS_ERRIF_Msk);
            goto exit_HSUSBD_IRQHandler;
        }

        if (IrqSt & HSUSBD_CEPINTSTS_STSDONEIF_Msk)
        {
            HSUSBD_UpdateDeviceState();
            HSUSBD_CLR_CEP_INT_FLAG(HSUSBD_CEPINTSTS_STSDONEIF_Msk);
            HSUSBD_ENABLE_CEP_INT(HSUSBD_CEPINTEN_SETUPPKIEN_Msk);
            goto exit_HSUSBD_IRQHandler;
        }

        if (IrqSt & HSUSBD_CEPINTSTS_BUFFULLIF_Msk)
        {
            HSUSBD_CLR_CEP_INT_FLAG(HSUSBD_CEPINTSTS_BUFFULLIF_Msk);
            goto exit_HSUSBD_IRQHandler;
        }

        if (IrqSt & HSUSBD_CEPINTSTS_BUFEMPTYIF_Msk)
        {
            HSUSBD_CLR_CEP_INT_FLAG(HSUSBD_CEPINTSTS_BUFEMPTYIF_Msk);
            goto exit_HSUSBD_IRQHandler;
        }
    }

    if (IrqStL & HSUSBD_GINTSTS_EPBIF_Msk)
    {
        NuML_CDC_HandleBulkIn();
        goto exit_HSUSBD_IRQHandler;
    }

    if (IrqStL & HSUSBD_GINTSTS_EPDIF_Msk)
    {
        NuML_CDC_HandleBulkOut();
        goto exit_HSUSBD_IRQHandler;
    }

    if (IrqStL & HSUSBD_GINTSTS_EPEIF_Msk)
    {
        HSUSBD_CLR_EP_INT_FLAG(EPE, HSUSBD->EP[EPE].EPINTSTS & HSUSBD->EP[EPE].EPINTEN);
        goto exit_HSUSBD_IRQHandler;
    }

exit_HSUSBD_IRQHandler:
    __DSB();
    __ISB();
}

/*----------------------------------------------------------------------------
 * Bring-up
 *--------------------------------------------------------------------------*/

static void NuML_USBD_EnableClockAndPhy(void)
{
    int i;

    SYS->USBPHY &= ~SYS_USBPHY_HSUSBROLE_Msk;    /* select HSUSBD */
    SYS->USBPHY = (SYS->USBPHY & ~(SYS_USBPHY_HSUSBROLE_Msk | SYS_USBPHY_HSUSBACT_Msk)) | SYS_USBPHY_HSOTGPHYEN_Msk;

    for (i = 0; i < 0x1000; i++)
    {
        __NOP();
    }

    SYS->USBPHY |= SYS_USBPHY_HSUSBACT_Msk;

    CLK_EnableModuleClock(HSUSBD0_MODULE);
}

void NuML_USBD_Init(void)
{
    SYS_UnlockReg();
    NuML_USBD_EnableClockAndPhy();
    SYS_LockReg();

    HSUSBD_Open(&gsNuMLHSInfo, NuML_USBD_ClassRequest, NuML_USBD_SetInterface);

    HSUSBD_ENABLE_USB_INT(HSUSBD_GINTEN_USBIEN_Msk |
                          HSUSBD_GINTEN_CEPIEN_Msk |
                          NuML_CDC_GlobalIntMask());
    HSUSBD_ENABLE_BUS_INT(HSUSBD_BUSINTEN_DMADONEIEN_Msk |
                          HSUSBD_BUSINTEN_RESUMEIEN_Msk |
                          HSUSBD_BUSINTEN_RSTIEN_Msk |
                          HSUSBD_BUSINTEN_VBUSDETIEN_Msk);
    HSUSBD_SET_ADDR(0);

    /* Control endpoint */
    HSUSBD_SetEpBufAddr(CEP, 0x00, 0x40);
    HSUSBD_ENABLE_CEP_INT(HSUSBD_CEPINTEN_SETUPPKIEN_Msk | HSUSBD_CEPINTEN_STSDONEIEN_Msk);

    NuML_CDC_InitForHighSpeed();

    NVIC_EnableIRQ(HSUSBD_IRQn);
    HSUSBD_Start();
}
