/**************************************************************************//**
 * @file     numl_cdc.c
 * @brief    HSUSB CDC virtual COM port for a NuML project with no video function.
 *
 * Generated by NuML Application Builder v0.1.8 -- do not edit by hand.
 * Every Generate and Build re-applies this file.
 * NUML_APP_BUILDER_USB_CDC_DEVICE_V0_1_8
 ******************************************************************************/

/* PIO ONLY.  HSUSBD has a single DMA engine and a single g_hsusbd_DmaDone
 * flag, both owned by the UVC ISO path (UVC_ActiveDMA busy-waits on it from
 * main context).  Touching DMACTL/DMAADDR/DMACNT here, or setting
 * g_hsusbd_DmaDone, would corrupt an in-flight video frame.
 */
#include <stdint.h>
#include <stddef.h>

#include "NuMicro.h"
#include "numl_cdc.h"

/* CDC ACM class requests (USB CDC 1.1 table 46). */
#define NUML_CDC_SET_LINE_CODE              0x20
#define NUML_CDC_GET_LINE_CODE              0x21
#define NUML_CDC_SET_CONTROL_LINE_STATE     0x22

typedef struct
{
    uint32_t u32DTERate;
    uint8_t  u8CharFormat;
    uint8_t  u8ParityType;
    uint8_t  u8DataBits;
} __attribute__((packed)) S_NUML_CDC_LINE_CODING;

/* Echoed back on GET_LINE_CODING.  The values are cosmetic: there is no real
 * UART behind this port, the host just insists on a valid answer. */
static volatile S_NUML_CDC_LINE_CODING s_sLineCoding = {115200ul, 0u, 0u, 8u};
static volatile uint16_t s_u16CtrlSignal = 0u;

#define NUML_CDC_RING_SIZE                  2048u

static volatile uint8_t  s_au8Ring[NUML_CDC_RING_SIZE];
static volatile uint32_t s_u32RingHead = 0u;    /* advanced by NuML_CdcRingPush */
static volatile uint32_t s_u32RingTail = 0u;    /* advanced by NuML_CDC_Pump    */
static volatile uint32_t s_u32Dropped  = 0u;
static volatile uint32_t s_u32TxBusy   = 0u;    /* set by Pump, cleared by ISR  */
static volatile uint8_t  s_u8ZlpPending = 0u;

uint32_t NuML_CDC_GlobalIntMask(void)
{
    return (HSUSBD_GINTEN_EPBIEN_Msk | HSUSBD_GINTEN_EPDIEN_Msk | HSUSBD_GINTEN_EPEIEN_Msk);
}

void NuML_CDC_Reset(void)
{
    /* A bus reset abandons any armed packet.  Without clearing the busy flag
     * the port stays permanently silent after the host re-enumerates. */
    s_u32TxBusy = 0u;
    s_u8ZlpPending = 0u;
}

static void NuML_CDC_ConfigEndpoints(uint32_t u32BulkMaxPacket)
{
    /* EPB ==> bulk IN, endpoint address 2 */
    HSUSBD_SetEpBufAddr(EPB, NUML_CDC_EPB_BUF_BASE, NUML_CDC_EPB_BUF_LEN);
    HSUSBD_SET_MAX_PAYLOAD(EPB, u32BulkMaxPacket);
    HSUSBD_ConfigEp(EPB, NUML_CDC_BULK_IN_EP_NUM, HSUSBD_EP_CFG_TYPE_BULK, HSUSBD_EP_CFG_DIR_IN);

    /* EPD ==> bulk OUT, endpoint address 4 */
    HSUSBD_SetEpBufAddr(EPD, NUML_CDC_EPD_BUF_BASE, NUML_CDC_EPD_BUF_LEN);
    HSUSBD_SET_MAX_PAYLOAD(EPD, u32BulkMaxPacket);
    HSUSBD_ConfigEp(EPD, NUML_CDC_BULK_OUT_EP_NUM, HSUSBD_EP_CFG_TYPE_BULK, HSUSBD_EP_CFG_DIR_OUT);
    HSUSBD_ENABLE_EP_INT(EPD, HSUSBD_EPINTEN_RXPKIEN_Msk);

    /* EPE ==> interrupt IN, endpoint address 5.  Declared so the host binds a
     * CDC-ACM driver; this firmware never sends a SERIAL_STATE notification. */
    HSUSBD_SetEpBufAddr(EPE, NUML_CDC_EPE_BUF_BASE, NUML_CDC_EPE_BUF_LEN);
    HSUSBD_SET_MAX_PAYLOAD(EPE, NUML_CDC_INT_MAX_PKT_SIZE);
    HSUSBD_ConfigEp(EPE, NUML_CDC_INT_IN_EP_NUM, HSUSBD_EP_CFG_TYPE_INT, HSUSBD_EP_CFG_DIR_IN);

    NuML_CDC_Reset();
}

void NuML_CDC_InitForHighSpeed(void)
{
    NuML_CDC_ConfigEndpoints(NUML_CDC_BULK_MAX_PKT_SIZE);
}

void NuML_CDC_InitForFullSpeed(void)
{
    NuML_CDC_ConfigEndpoints(NUML_CDC_BULK_OTHER_MAX_PKT_SIZE);
}

void NuML_CdcRingPush(uint8_t u8Char)
{
    uint32_t u32Next = (s_u32RingHead + 1u) % NUML_CDC_RING_SIZE;

    if (u32Next == s_u32RingTail)
    {
        /* No terminal attached, or the host stopped reading.  Drop the byte:
         * printf must never stall the inference loop. */
        s_u32Dropped++;
        return;
    }

    s_au8Ring[s_u32RingHead] = u8Char;
    s_u32RingHead = u32Next;
}

void NuML_CDC_Pump(void)
{
    uint32_t u32Len = 0u;

    if (s_u32TxBusy != 0u)
    {
        return;     /* the previous packet has not been collected yet */
    }

    while ((s_u32RingTail != s_u32RingHead) && (u32Len < NUML_CDC_BULK_MAX_PKT_SIZE))
    {
        HSUSBD->EP[EPB].EPDAT_BYTE = s_au8Ring[s_u32RingTail];
        s_u32RingTail = (s_u32RingTail + 1u) % NUML_CDC_RING_SIZE;
        u32Len++;
    }

    if (u32Len == 0u)
    {
        /* Terminate only a transfer that ended on a full-size packet.  Arming
         * a zero-length packet every idle iteration would produce a continuous
         * stream of IN-token interrupts competing with UVC ISO servicing. */
        if (s_u8ZlpPending == 0u)
        {
            return;
        }

        s_u8ZlpPending = 0u;
    }
    else
    {
        s_u8ZlpPending = (u32Len == NUML_CDC_BULK_MAX_PKT_SIZE) ? 1u : 0u;
    }

    s_u32TxBusy = 1u;
    HSUSBD->EP[EPB].EPRSPCTL = HSUSBD_EP_RSPCTL_SHORTTXEN;
    HSUSBD->EP[EPB].EPTXCNT = u32Len;
    HSUSBD_ENABLE_EP_INT(EPB, HSUSBD_EPINTEN_INTKIEN_Msk);
}

void NuML_CDC_HandleBulkIn(void)
{
    uint32_t u32IrqSt = HSUSBD->EP[EPB].EPINTSTS & HSUSBD->EP[EPB].EPINTEN;

    s_u32TxBusy = 0u;
    HSUSBD_ENABLE_EP_INT(EPB, 0);
    HSUSBD_CLR_EP_INT_FLAG(EPB, u32IrqSt);
}

void NuML_CDC_HandleBulkOut(void)
{
    uint32_t u32IrqSt = HSUSBD->EP[EPD].EPINTSTS & HSUSBD->EP[EPD].EPINTEN;
    uint32_t u32Len = HSUSBD->EP[EPD].EPDATCNT & 0xfffful;
    uint32_t i;
    volatile uint8_t u8Discard = 0u;

    /* This port is a one-way printf sink.  Drain whatever the host writes so
     * the endpoint cannot wedge, but do not interpret it. */
    for (i = 0u; i < u32Len; i++)
    {
        u8Discard = HSUSBD->EP[EPD].EPDAT_BYTE;
    }

    (void)u8Discard;
    HSUSBD_CLR_EP_INT_FLAG(EPD, u32IrqSt);
}

int NuML_CDC_ClassRequest(void)
{
    if ((gUsbCmd.wIndex & 0xfful) != NUML_CDC_COMM_INTERFACE)
    {
        return 0;   /* not ours: let the UVC handler stall exactly as before */
    }

    if (gUsbCmd.bmRequestType & 0x80u)
    {
        if (gUsbCmd.bRequest == NUML_CDC_GET_LINE_CODE)
        {
            HSUSBD_PrepareCtrlIn((uint8_t *)&s_sLineCoding, 7ul);
            HSUSBD_CLR_CEP_INT_FLAG(HSUSBD_CEPINTSTS_INTKIF_Msk);
            HSUSBD_ENABLE_CEP_INT(HSUSBD_CEPINTEN_INTKIEN_Msk);
            return 1;
        }

        return 0;
    }

    if (gUsbCmd.bRequest == NUML_CDC_SET_CONTROL_LINE_STATE)
    {
        s_u16CtrlSignal = gUsbCmd.wValue;   /* bit0 DTR, bit1 RTS */
        HSUSBD_CLR_CEP_INT_FLAG(HSUSBD_CEPINTSTS_STSDONEIF_Msk);
        HSUSBD_SET_CEP_STATE(HSUSBD_CEPCTL_NAKCLR);
        HSUSBD_ENABLE_CEP_INT(HSUSBD_CEPINTEN_STSDONEIEN_Msk);
        return 1;
    }

    if (gUsbCmd.bRequest == NUML_CDC_SET_LINE_CODE)
    {
        /* Same flow as the BSP HSUSBD_VCOM_SerialEmulator sample.  Note that
         * HSUSBD_CtrlOut() busy-waits and this runs inside the USB ISR; the
         * host sends these 7 bytes in the next microframe, so the pause in
         * UVC ISO servicing is bounded to a frame or two at port open. */
        HSUSBD_CtrlOut((uint8_t *)&s_sLineCoding, 7ul);
        HSUSBD_CLR_CEP_INT_FLAG(HSUSBD_CEPINTSTS_STSDONEIF_Msk);
        HSUSBD_SET_CEP_STATE(HSUSBD_CEPCTL_NAKCLR);
        HSUSBD_ENABLE_CEP_INT(HSUSBD_CEPINTEN_STSDONEIEN_Msk);
        return 1;
    }

    return 0;
}

int NuML_CDC_IsOpen(void)
{
    return (s_u16CtrlSignal & 0x0001u) ? 1 : 0;
}

uint32_t NuML_CDC_DroppedBytes(void)
{
    return s_u32Dropped;
}

/* Modified for Teachable Machine Local Studio: see the header comment. */
int NuML_CDC_Pending(void)
{
    return (s_u32RingTail != s_u32RingHead) || (s_u32TxBusy != 0u);
}
