from __future__ import annotations

from pathlib import Path

import pytest

from tm_local.mcu import boards, contract, paths
from tm_local.mcu.apps import image as image_app
from tm_local.mcu.errors import DeployError

TEMPLATES = paths.APPS_ROOT / "image"
pytestmark = pytest.mark.skipif(
    not (TEMPLATES / "NuGestureAI-M55M1" / "main.cpp.in").is_file(),
    reason="image templates not vendored",
)


def _contract(board_name: str, tmp_path: Path) -> contract.DeployContract:
    return contract.DeployContract(
        kind="image",
        application="imgclass",
        board=boards.board_for(board_name),
        project_id="p",
        project_name="n",
        labels=["a", "b"],
        models_dir=tmp_path,
        int8_path=tmp_path / "m.tflite",
        model_sha256="x",
        input=contract.TensorInfo("in", (1, 128, 128, 3), "int8", 1.0, -128),
        output=contract.TensorInfo("out", (1, 2), "int8", 0.0039, -128),
        image_size=128,
        audio_frontend=None,
        yamnet_frontend=None,
        encoder_depth=None,
        detection_threshold=0.5,
        class_thresholds=[0.5, 0.5],
        hop_seconds=0.5,
        clip_seconds=1.0,
        peak_hold_seconds=1.5,
    )


class _Vela:
    arena_bytes = 183296


@pytest.mark.parametrize("board", ["NuMaker-M55M1", "NuGestureAI-M55M1"])
def test_template_markers(board: str) -> None:
    text = (TEMPLATES / board / "main.cpp.in").read_text(encoding="utf-8")
    assert "@@ARENA@@" in text and "__ARENA_TOKEN__" not in text
    for marker in (
        "NuML_FindTop1",
        "char predictLabelInfo[160]",
        "static const ARM_MPU_Region_t mpuConfig[]",
        "//#define __LOAD_MODEL_FROM_SD__",
        "centre crop",
    ):
        assert marker in text, marker
    if board == "NuGestureAI-M55M1":
        assert "NuML_Overlay_DrawText565" in text and "NuML_CDC_Pump();" in text
        assert '#include "numl_cdc.h"' in text
        uvc = paths.template_dir(board, "imgclass") / "NN_ImgClassInference" / "Device" / "UVC"
        assert "NuML_CDC_ClassRequest" in (uvc / "UVC.c").read_text(encoding="utf-8")
        assert "0x9A, 0x01," in (uvc / "descriptors.c").read_text(encoding="utf-8")
    else:
        assert "numl_cdc" not in text and "//#define __USE_UVC__" in text


@pytest.mark.parametrize("board", ["NuMaker-M55M1", "NuGestureAI-M55M1"])
def test_template_header_and_single_arena_define(board: str) -> None:
    text = (TEMPLATES / board / "main.cpp.in").read_text(encoding="utf-8")
    assert text.startswith("/* Generated by scripts/vendor_image_templates.py")
    assert "\r\n" not in text
    # The template must carry exactly one arena definition, fed only by Vela.
    assert text.count("#define ACTIVATION_BUF_SZ") == 1
    assert "#define ACTIVATION_BUF_SZ (@@ARENA@@)" in text
    assert "#undef ACTIVATION_BUF_SZ" in text
    assert "0x100000" not in text


@pytest.mark.parametrize("board", ["NuMaker-M55M1", "NuGestureAI-M55M1"])
def test_centre_crop_replaces_only_the_model_input_roi(board: str) -> None:
    text = (TEMPLATES / board / "main.cpp.in").read_text(encoding="utf-8")
    assert text.count("centre crop, matches Studio training") == 1
    assert text.count("roi.h = roi.w;") == 1
    crop = text.index("centre crop, matches Studio training")
    resize = text.index("resizeImg.w = inputImgCols;")
    assert crop < resize, "the centre crop must precede the model-input resize"
    # The UVC RGB565 -> YUY2 full-frame ROI is untouched.
    assert "roi.w = RGB565Img.w;" in text
    assert "roi.w = frameBuffer.w;" not in text


@pytest.mark.parametrize("board", ["NuMaker-M55M1", "NuGestureAI-M55M1"])
def test_prepare_and_overlay(board: str, tmp_path: Path) -> None:
    app = tmp_path / "NN_ImgClassInference"
    (app / "Device" / "include").mkdir(parents=True)
    c = _contract(board, tmp_path)
    image_app.prepare(c, _Vela(), app)
    main = (app / "main.cpp").read_text(encoding="utf-8")
    assert "#define ACTIVATION_BUF_SZ (183296)" in main and "@@" not in main
    overlay = image_app.overlay(c)
    if board == "NuGestureAI-M55M1":
        assert (app / "Device" / "CDC" / "numl_cdc.c").is_file()
        assert (app / "Device" / "include" / "numl_overlay.h").is_file()
        assert (app / "Device" / "include" / "numl_cdc.h").is_file()
        assert (app / "Device" / "CDC" / "numl_cdc_retarget.c").is_file()
        assert (app / "Device" / "CDC" / "numl_overlay.c").is_file()
        assert [p.name for p in overlay["add_sources"]] == [
            "numl_cdc.c",
            "numl_cdc_retarget.c",
            "numl_overlay.c",
        ]
        assert [str(p.parent) for p in overlay["add_sources"]] == [str(Path("Device") / "CDC")] * 3
        assert overlay["remove_source_basenames"] == ["retarget.c"]
        assert overlay["add_includes"] == [paths.BSP_ROOT / "Library" / "StdDriver" / "src"]
    else:
        assert overlay == {}
        assert not (app / "Device" / "CDC").exists()


def test_prepare_creates_missing_device_dirs(tmp_path: Path) -> None:
    app = tmp_path / "NN_ImgClassInference"
    app.mkdir()
    image_app.prepare(_contract("NuGestureAI-M55M1", tmp_path), _Vela(), app)
    assert (app / "Device" / "include" / "numl_cdc.h").is_file()
    assert (app / "Device" / "CDC" / "numl_overlay.c").is_file()


def test_template_path_rejects_unknown_board() -> None:
    with pytest.raises(DeployError):
        image_app.template_path("NoSuchBoard")
