"""Binds ``tm_local.yamnet_model.frontend_contract()`` to the vendored known_sound C frontend.

CLAUDE.md architecture decision 11: every MCU-side constant is generated from the training-time
contract at deploy time, never hand-synced. The audio/KWS path honours this literally --
``kws_codegen.kws_tables()`` calls the training-time ``audio_frontend.mel_filterbank()`` directly
at deploy time, so the PC and the board can never compute a different spectrogram. The known_sound
YAMNet C frontend (``mcu_toolkit/apps/known_sound/frontend/numl_yamnet_frontend.{h,c}``) does not
honour it the same way: its ``#define`` constants were hand-copied out of
``tm_local.yamnet_model.frontend_contract()`` once when the frontend was authored, and nothing in
the repository would notice if the two drifted apart afterwards.

This module is that missing binding. It is deliberately *not* a codegen rewrite, and it never
touches the vendored header/source -- both are generator output per ``scripts/vendor_mcu_toolkit.py``
and are outside this test's job. It only *reads* them, alongside the golden fixture that the
vendored C frontend's own host test already trusts
(``mcu_toolkit/apps/known_sound/host_tests/golden/golden_meta.json``), and cross-checks every value
against ``frontend_contract()``.

Unlike ``tests/test_known_sound_frontend_host.py`` -- which module-level ``skipif``s without MSVC
Build Tools, because it needs to actually compile and run the C frontend -- nothing in this file
needs a C compiler: it only parses text (a JSON file and two small C/C++ source files) and compares
plain Python values. So nothing here may ever ``pytest.skip``. A missing or unreadable vendored
file must fail loudly (``FileNotFoundError`` propagating out of a fixture), not be treated as an
environment limitation the way the host test treats a missing compiler.
"""

from __future__ import annotations

import json
import re
from typing import Any

import pytest

from tm_local.mcu.paths import APPS_ROOT
from tm_local.yamnet_model import frontend_contract

FRONTEND_DIR = APPS_ROOT / "known_sound" / "frontend"
HEADER_PATH = FRONTEND_DIR / "numl_yamnet_frontend.h"
SOURCE_PATH = FRONTEND_DIR / "numl_yamnet_frontend.c"
GOLDEN_META_PATH = APPS_ROOT / "known_sound" / "host_tests" / "golden" / "golden_meta.json"

# Matches e.g. "#define NUML_YAMNET_SAMPLE_RATE      16000" -> ("NUML_YAMNET_SAMPLE_RATE", "16000").
# Deliberately requires a numeric value after the name, so the include guard
# ("#define NUML_YAMNET_FRONTEND_H", no value) is never captured.
_DEFINE_INT_RE = re.compile(r"#define\s+(NUML_YAMNET_\w+)\s+(\d+)\b")
# Matches e.g. "#define NUML_LOG_OFFSET_F  0.001f" -> "0.001". This one constant lives in the
# .c file, not the .h, because it is only used inside NuML_Yamnet_LogMel()'s implementation.
_LOG_OFFSET_RE = re.compile(r"#define\s+NUML_LOG_OFFSET_F\s+([0-9.]+)f")


def _parse_header_defines() -> dict[str, int]:
    text = HEADER_PATH.read_text(encoding="utf-8")
    defines = {name: int(value) for name, value in _DEFINE_INT_RE.findall(text)}
    # A vendored header that changed shape enough that nothing matched would otherwise make
    # every comparison below vacuously true (missing key -> KeyError -> test failure is fine,
    # but an *empty* dict combined with a test that only checks a subset would not be).
    assert defines, f"no NUML_YAMNET_* #define parsed out of {HEADER_PATH}"
    return defines


def _parse_log_offset() -> float:
    text = SOURCE_PATH.read_text(encoding="utf-8")
    match = _LOG_OFFSET_RE.search(text)
    assert match, f"NUML_LOG_OFFSET_F not found in {SOURCE_PATH}"
    return float(match.group(1))


def _golden_config() -> dict[str, Any]:
    data = json.loads(GOLDEN_META_PATH.read_text(encoding="utf-8"))
    return data["config"]


@pytest.fixture(scope="module")
def contract() -> dict[str, Any]:
    return frontend_contract()


@pytest.fixture(scope="module")
def defines() -> dict[str, int]:
    return _parse_header_defines()


@pytest.fixture(scope="module")
def log_offset_f() -> float:
    return _parse_log_offset()


@pytest.fixture(scope="module")
def golden() -> dict[str, Any]:
    return _golden_config()


# ---------------------------------------------------------------------------
# frontend_contract() <-> golden_meta.json["config"]
#
# golden_meta.json is generated by the vendored host-test tooling
# (mcu_toolkit/apps/known_sound/host_tests/) as the reference the compiled C frontend's own
# output is checked against. If this file and frontend_contract() disagree, the host test is
# validating the C frontend against the wrong target.
# ---------------------------------------------------------------------------


@pytest.mark.parametrize(
    "key",
    [
        "sample_rate",
        "fft_length",
        "mel_bands",
        "mel_min_hz",
        "mel_max_hz",
        "log_offset",
        "patch_frames",
        "patch_hop_frames",
    ],
)
def test_contract_matches_golden_direct(contract, golden, key) -> None:
    """These keys share the same name and the same value in both places."""

    assert contract[key] == pytest.approx(golden[key]), (
        f"frontend_contract()[{key!r}] = {contract[key]!r} but "
        f"golden_meta.json['config'][{key!r}] = {golden[key]!r}"
    )


def test_contract_matches_golden_frame_length(contract, golden) -> None:
    frame_length = contract["stft_window_seconds"] * contract["sample_rate"]
    assert frame_length == golden["frame_length"]


def test_contract_matches_golden_frame_step(contract, golden) -> None:
    frame_step = contract["stft_hop_seconds"] * contract["sample_rate"]
    assert frame_step == golden["frame_step"]


def test_contract_matches_golden_spectrogram_bins(contract, golden) -> None:
    spectrogram_bins = contract["fft_length"] // 2 + 1
    assert spectrogram_bins == golden["spectrogram_bins"]


def test_contract_matches_golden_clip_samples(contract, golden) -> None:
    clip_samples = contract["inference_window_seconds"] * contract["sample_rate"]
    assert clip_samples == golden["clip_samples"]


# ---------------------------------------------------------------------------
# frontend_contract() <-> numl_yamnet_frontend.h / numl_yamnet_frontend.c #define values
# ---------------------------------------------------------------------------


def test_c_sample_rate(contract, defines) -> None:
    assert defines["NUML_YAMNET_SAMPLE_RATE"] == contract["sample_rate"]


def test_c_frame_length(contract, defines) -> None:
    expected = int(round(contract["stft_window_seconds"] * contract["sample_rate"]))
    assert defines["NUML_YAMNET_FRAME_LENGTH"] == expected


def test_c_frame_step(contract, defines) -> None:
    expected = int(round(contract["stft_hop_seconds"] * contract["sample_rate"]))
    assert defines["NUML_YAMNET_FRAME_STEP"] == expected


def test_c_fft_length(contract, defines) -> None:
    assert defines["NUML_YAMNET_FFT_LENGTH"] == contract["fft_length"]


def test_c_spectrum_bins(contract, defines) -> None:
    expected = contract["fft_length"] // 2 + 1
    assert defines["NUML_YAMNET_SPECTRUM_BINS"] == expected


def test_c_mel_bands(contract, defines) -> None:
    assert defines["NUML_YAMNET_MEL_BANDS"] == contract["mel_bands"]


def test_c_patch_frames(contract, defines) -> None:
    assert defines["NUML_YAMNET_PATCH_FRAMES"] == contract["patch_frames"]


def test_c_clip_samples(contract, defines) -> None:
    expected = int(round(contract["inference_window_seconds"] * contract["sample_rate"]))
    assert defines["NUML_YAMNET_CLIP_SAMPLES"] == expected


def test_c_clip_frames(contract, defines) -> None:
    """NUML_YAMNET_CLIP_FRAMES has no frontend_contract() key of its own: it's the number of
    STFT frames one NUML_YAMNET_CLIP_SAMPLES-long clip yields, using the same
    "(samples - window) // hop + 1" framing formula numl_yamnet_frontend.c itself uses.
    """

    clip_samples = int(round(contract["inference_window_seconds"] * contract["sample_rate"]))
    frame_length = int(round(contract["stft_window_seconds"] * contract["sample_rate"]))
    frame_step = int(round(contract["stft_hop_seconds"] * contract["sample_rate"]))
    expected = (clip_samples - frame_length) // frame_step + 1
    assert defines["NUML_YAMNET_CLIP_FRAMES"] == expected


def test_c_log_offset(contract, log_offset_f) -> None:
    assert log_offset_f == pytest.approx(contract["log_offset"])


def test_model_input_shape(contract, defines) -> None:
    """tm_local/mcu/contract.py derives its expected known_sound input shape as
    ``(1, *frontend_contract()["model_input_shape"])``. Pin down what the two numbers in that
    2-element list actually mean against the C side, so a future edit to either the list's
    order or its values cannot silently swap frames and mel bands.
    """

    assert contract["model_input_shape"] == [
        defines["NUML_YAMNET_PATCH_FRAMES"],
        defines["NUML_YAMNET_MEL_BANDS"],
    ]
