"""The vendored Known Sound firmware pack: files, token contract, per-class thresholds, build.

`main.cpp.in` is produced once by `scripts/vendor_known_sound.py` from the App Builder's
`known_sound_runtime._MAIN_TEMPLATE`. Every App Builder placeholder that the Studio does not
render at deploy time must already be resolved here, because `tm_local.mcu.codegen.render_tokens`
refuses a template with any leftover `@@TOKEN@@` -- so the token set is asserted exactly, not
just "these seven are present".
"""
from __future__ import annotations

import re
import shutil
import subprocess
import sys
from pathlib import Path

import pytest

from tm_local.mcu import boards as boards_module
from tm_local.mcu import paths
from tm_local.mcu.apps import known_sound

PACK = paths.APPS_ROOT / "known_sound"
DEPLOY_TOKENS = (
    "@@ARENA@@",
    "@@CLASS_COUNT@@",
    "@@CLIP_SAMPLES@@",
    "@@HOP_SAMPLES@@",
    "@@HOLD_HOPS@@",
    "@@LABELS@@",
    "@@THRESHOLDS@@",
)

pytestmark = pytest.mark.skipif(
    not (PACK / "main.cpp.in").is_file(), reason="known_sound pack not vendored"
)

_CREATE_NO_WINDOW = getattr(subprocess, "CREATE_NO_WINDOW", 0)


def _main_template() -> str:
    return (PACK / "main.cpp.in").read_text(encoding="utf-8")


def test_pack_files_present() -> None:
    for rel in (
        "frontend/numl_yamnet_frontend.c",
        "frontend/numl_yamnet_frontend.h",
        "frontend/numl_yamnet_tables.h",
        "frontend/numl_known_sound.c",
        "frontend/numl_known_sound.h",
        "device/numl_dmic.c",
        "device/numl_dmic.h",
        "device/BoardConfig.h",
        "main.cpp.in",
        "README.md",
        "host_tests/harness.py",
        "host_tests/make_tables.py",
        "host_tests/golden/golden.npz",
        "host_tests/golden/golden_meta.json",
        "host_tests/golden/scores.npz",
        "host_tests/golden/scores_meta.json",
    ):
        assert (PACK / rel).is_file(), rel
    # The board-specific BoardInit/model/vector sources belong to the App Builder's own project,
    # not to the Studio's; vendoring them would ship a second, stale model.
    for unwanted in ("device/main.cpp", "device/KnownSoundModelData.cpp", "device/known_sound_vectors.c"):
        assert not (PACK / unwanted).exists(), unwanted
    # Dead weight deliberately left behind: the App Builder's own two test modules resolve
    # ROOT/model/ and ROOT/golden/ paths that do not exist in this layout (their assertions live
    # in tests/test_known_sound_frontend_host.py), and nothing here reads the 192 KiB of source
    # recordings the golden vectors were extracted from.
    for unwanted in ("host_tests/test_frontend.py", "host_tests/test_postprocess.py"):
        assert not (PACK / unwanted).exists(), unwanted
    assert not (PACK / "host_tests" / "golden" / "wav").exists()
    assert not list(PACK.rglob("*.wav"))


def test_main_template_is_generated_and_lf_only() -> None:
    raw = (PACK / "main.cpp.in").read_bytes()
    assert b"\r\n" not in raw
    first = raw.split(b"\n", 1)[0].decode("utf-8")
    assert "Generated by scripts/vendor_known_sound.py" in first
    assert "known_sound_runtime._MAIN_TEMPLATE" in first


def test_main_template_tokens_and_per_class_threshold() -> None:
    text = _main_template()
    for token in DEPLOY_TOKENS:
        assert token in text, token
    # render_tokens() raises on ANY leftover @@TOKEN@@, so nothing else may survive vendoring.
    assert set(re.findall(r"@@[A-Z0-9_]+@@", text)) == set(DEPLOY_TOKENS)
    assert "@@THRESHOLD@@" not in text
    assert "@@MODEL_" not in text
    assert "KNOWN_SOUND_THRESHOLD" not in text


def test_per_class_threshold_array_replaces_the_single_define() -> None:
    text = _main_template()
    assert "static const float s_afThreshold[KNOWN_SOUND_CLASSES] =\n{\n@@THRESHOLDS@@\n};" in text
    assert "/* One independent sigmoid threshold per class (Studio class_thresholds). */" in text
    assert "int aiThresholdCode[KNOWN_SOUND_CLASSES];" in text
    assert "aiThresholdCode[i] = NuML_KnownSound_ThresholdCode(" in text
    assert "s_afThreshold[i], psOutput->params.scale, psOutput->params.zero_point);" in text
    assert '(psOutput->data.int8[i] >= aiThresholdCode[i]) ? "*" : " "' in text
    # The single shared threshold code is gone: `\b` before `i` does not match inside
    # `aiThresholdCode`, so this catches a surviving scalar use without false-positiving.
    assert re.search(r"\biThresholdCode\b", text) is None
    assert 'printf("INFO threshold[%s] %.2f -> output code >= %d\\n",' in text
    # Multi-label, not a distribution: every class is judged against its own threshold, and the
    # runtime says so where the next reader of this firmware will look.
    assert "not a probability distribution" in text
    assert "NuML_KnownSound_Scores(" in text


def test_main_template_model_symbols_match_studio_codegen() -> None:
    text = _main_template()
    # `const`, matching codegen.model_cpp_text()'s definition; see
    # tests/test_mcu_codegen.py::test_model_pointer_declaration_is_const_in_every_app_template.
    assert "extern const uint8_t *GetModelPointer();" in text
    assert "extern uint8_t *GetModelPointer();" not in text
    assert "extern size_t GetModelLen();" in text
    assert "arm::app::nn::GetModelPointer()" in text
    assert "arm::app::nn::GetModelLen()" in text
    assert "(unsigned)arm::app::nn::GetModelLen()" in text
    # Model-from-SD is not a Studio deployment mode; the internal-flash init is baked in.
    assert "ModelFileReader" not in text and "MODEL_AT_HYPERRAM_ADDR" not in text
    assert "BOARD_LOG_INIT();" in text and "BOARD_LOG_PUMP();" in text
    assert "TEACHABLE_MACHINE_LOCAL_STUDIO_KNOWN_SOUND_RUNTIME_V1" in text


def test_board_config_has_every_board() -> None:
    """Every board known_sound.BOARD_DEFINE registers must get its own #if branch and DMIC
    pins in BoardConfig.h -- derived from the registries, not a hardcoded board count, so a
    newly-added board (e.g. NuMaker-VoiceAI-M55M1) is automatically covered."""
    text = (PACK / "device" / "BoardConfig.h").read_text(encoding="utf-8")
    board_table = boards_module.load_boards()
    for name, define in known_sound.BOARD_DEFINE.items():
        assert define in text, define
        dmic = board_table[name].audio_dmic
        assert f"{dmic.clk_macro}()" in text, (name, dmic.clk_macro)
        assert f"{dmic.dat_macro}()" in text, (name, dmic.dat_macro)
        assert dmic.channel_mask in text, (name, dmic.channel_mask)


def test_board_config_dmic_matches_boards_json() -> None:
    """boards.json is what the deploy step reports; BoardConfig.h is what actually compiles."""
    import json

    boards = json.loads(paths.BOARDS_JSON.read_text(encoding="utf-8"))
    text = (PACK / "device" / "BoardConfig.h").read_text(encoding="utf-8")
    for board, define in known_sound.BOARD_DEFINE.items():
        dmic = boards[board]["audio_dmic"]
        # Anchor on the block opener (`#if`/`#elif defined(...)`), not on any `defined(...)`:
        # the file opens with a `#if !defined(A) && !defined(B) && !defined(C)` default-board
        # guard.
        opener = re.search(rf"(?m)^#(?:el)?if defined\({define}\)$", text)
        assert opener is not None, define
        block = text[opener.end() :].split("#elif", 1)[0]
        assert f"{dmic['clk_macro']}()" in block, board
        assert f"{dmic['dat_macro']}()" in block, board
        assert f"#define BOARD_DMIC_CHANNEL      {dmic['channel']}" in block, board


@pytest.mark.parametrize("board_define", list(known_sound.BOARD_DEFINE.values()))
def test_pack_sources_compile_with_arm_gcc(board_define: str, tmp_path: Path) -> None:
    gcc = shutil.which("arm-none-eabi-gcc")
    if not gcc or not paths.toolkit_available():
        pytest.skip("toolchain or toolkit missing")
    bsp = paths.BSP_ROOT
    includes = [
        PACK / "frontend",
        PACK / "device",
        paths.APPS_ROOT / "common" / "cdc" / "cdc_only",
        bsp / "Library/StdDriver/inc",
        bsp / "Library/Device/Nuvoton/M55M1/Include",
        bsp / "Library/CMSIS/Core/Include",
    ]
    for src in (
        PACK / "frontend" / "numl_yamnet_frontend.c",
        PACK / "frontend" / "numl_known_sound.c",
        PACK / "device" / "numl_dmic.c",
    ):
        cmd = [
            gcc, "-mcpu=cortex-m55", "-mthumb", "-mfloat-abi=hard", "-O1", "-std=c11",
            "-Wall", "-Wextra", "-Werror", f"-D{board_define}", "-DNVT_VECTOR_ON_FLASH",
            "-c", str(src), "-o", str(tmp_path / (src.stem + ".o")),
        ]
        cmd += [f"-I{p}" for p in includes]
        proc = subprocess.run(
            cmd, capture_output=True, text=True, timeout=120, cwd=tmp_path, check=False,
            creationflags=_CREATE_NO_WINDOW if sys.platform == "win32" else 0,
        )
        assert proc.returncode == 0, f"{src.name}: {proc.stderr}"
