/**************************************************************************//**
 * @file     numl_overlay.h
 * @brief    RGB565 frame-buffer text overlay for LCD-less boards.
 *
 * Generated by NuML Application Builder v0.1.8 -- do not edit by hand.
 * Every Generate and Build re-applies this file.
 * NUML_APP_BUILDER_USB_CDC_RUNTIME_V0_1_8
 ******************************************************************************/
#ifndef __NUML_OVERLAY_H__
#define __NUML_OVERLAY_H__

#include <stdint.h>

#ifdef __cplusplus
extern "C" {
#endif

#define NUML_OVERLAY_GLYPH_W    8u
#define NUML_OVERLAY_GLYPH_H    16u

/* Draws 8x16 text straight into an RGB565 frame buffer.  No LCD driver and no
 * hardware access: this board has no panel, the pixels leave over HSUSB UVC. */
void NuML_Overlay_DrawText565(void *pvFrameBuffer,
                              uint32_t u32Width,
                              uint32_t u32Height,
                              uint32_t u32X,
                              uint32_t u32Y,
                              const char *szText);

#ifdef __cplusplus
}
#endif

#endif  /* __NUML_OVERLAY_H__ */
