/* Modified for Teachable Machine Local Studio: GCC printf tee seam. */
/**************************************************************************//**
 * @file     numl_cdc_retarget.c
 * @brief    printf retarget: tee stdout to the USB CDC port and UART5.
 *
 * Generated by NuML Application Builder v0.1.8 -- do not edit by hand.
 * Every Generate and Build re-applies this file.
 * NUML_APP_BUILDER_USB_CDC_RUNTIME_V0_1_8
 ******************************************************************************/

/* Path depth: this file lives in
 *   <project>/NN_ImgClassInference/Device/CDC/
 * and the BSP root is five levels up.
 */

/* retarget.c:34-36 - defining any RTE_CMSIS_Compiler_* macro suppresses its
 * own #include of the compiler-specific _sys_* layer, for this TU only. */
#define RTE_CMSIS_Compiler_STDOUT 1

/* Rename the BSP's three sinks so they become private UART-only helpers and
 * leave the real names free for the tee below. */
#define stdout_putchar  NuML_UartPutchar
#define stdin_getchar   NuML_UartGetchar
#define stderr_putchar  NuML_UartPutcharErr

#include "retarget.c"

#undef stdout_putchar
#undef stdin_getchar
#undef stderr_putchar

/* The _sys_* layer calls these before this file defines them, and C99 has no
 * implicit declarations, so they must be prototyped here. */
extern int stdout_putchar(int ch);
extern int stdin_getchar(void);
extern int stderr_putchar(int ch);

/* Pull in the _sys_* layer here instead, so its call to stdout_putchar binds
 * to the tee below rather than to the UART-only helper.  Without this the C
 * library falls back to its own semihosting _sys_write and printf silently
 * goes nowhere -- with no link error. */
#if defined (__ARMCC_VERSION)
    #include "../../Device/Nuvoton/M55M1/Source/ARM/retarget_ARMCC.c"
#elif defined(__GNUC__)
    #undef stdout_putchar
    #undef stdin_getchar
    #undef stderr_putchar
    int stdout_putchar(int ch);   /* tee defined below; retarget_GCC.c's _write() must bind to it */
    #include "../../Device/Nuvoton/M55M1/Source/GCC/retarget_GCC.c"
#endif

#include "numl_cdc.h"

int stdout_putchar(int ch)
{
    /* USB first and non-blocking, then the original UART path so a serial
     * probe on the debug header keeps working when no USB host is attached.
     *
     * The BSP's UART sink (SendChar_ToUART) expands LF to CRLF itself, so it
     * still gets the untranslated character; the CDC ring has no such sink and
     * must do the expansion here, or every printf line starts where the last
     * one ended in the host's terminal.  A ring that fills between the two
     * pushes drops the LF the same way it already drops any other byte. */
    if ((char)ch == '\n')
    {
        NuML_CdcRingPush((uint8_t)'\r');
    }

    NuML_CdcRingPush((uint8_t)ch);
    return NuML_UartPutchar(ch);
}

int stderr_putchar(int ch)
{
    return stdout_putchar(ch);
}

int stdin_getchar(void)
{
    return NuML_UartGetchar();
}
