/**************************************************************************//**
 * @file     numl_cdc.h
 * @brief    CDC ACM virtual COM port sharing the HSUSB device with UVC.
 *
 * Generated by NuML Application Builder v0.1.8 -- do not edit by hand.
 * Every Generate and Build re-applies this file.
 * NUML_APP_BUILDER_USB_CDC_RUNTIME_V0_1_8
 ******************************************************************************/
#ifndef __NUML_CDC_H__
#define __NUML_CDC_H__

#include <stdint.h>

#ifdef __cplusplus
extern "C" {
#endif

/* UVC owns interfaces 0/1 and endpoint numbers 1 (ISO IN) and 3 (INT IN). */
#define NUML_CDC_COMM_INTERFACE             2
#define NUML_CDC_DATA_INTERFACE             3

#define NUML_CDC_BULK_IN_EP_NUM             0x02
#define NUML_CDC_BULK_OUT_EP_NUM            0x04
#define NUML_CDC_INT_IN_EP_NUM              0x05

#define NUML_CDC_BULK_MAX_PKT_SIZE          512
#define NUML_CDC_BULK_OTHER_MAX_PKT_SIZE    64
#define NUML_CDC_INT_MAX_PKT_SIZE           16

/* HSUSBD endpoint SRAM is 4096 bytes.  UVC holds CEP 0x000-0x03F,
 * EPA 0x200-0x9FF and EPC 0xE00-0xE07; these are the remaining holes. */
#define NUML_CDC_EPB_BUF_BASE               0xA00
#define NUML_CDC_EPB_BUF_LEN                0x200
#define NUML_CDC_EPD_BUF_BASE               0xC00
#define NUML_CDC_EPD_BUF_LEN                0x200
#define NUML_CDC_EPE_BUF_BASE               0xE08
#define NUML_CDC_EPE_BUF_LEN                0x010

/* Endpoint interrupt bits the CDC function needs OR-ed into GINTEN. */
uint32_t NuML_CDC_GlobalIntMask(void);

void NuML_CDC_InitForHighSpeed(void);
void NuML_CDC_InitForFullSpeed(void);
void NuML_CDC_Reset(void);

/* Returns 1 when the setup packet belonged to the CDC function and was
 * answered, 0 when the caller must fall through to its own STALL. */
int  NuML_CDC_ClassRequest(void);

void NuML_CDC_HandleBulkIn(void);
void NuML_CDC_HandleBulkOut(void);

/* Main-context pump: moves the ring buffer into the bulk IN endpoint. */
void NuML_CDC_Pump(void);

/* Non-blocking; drops when the host is not draining. */
void NuML_CdcRingPush(uint8_t u8Char);

int      NuML_CDC_IsOpen(void);
uint32_t NuML_CDC_DroppedBytes(void);

#ifdef __cplusplus
}
#endif

#endif  /* __NUML_CDC_H__ */
