"""Turn the exported mel filterbank into a compact C table.

The matrix is *exported*, never reimplemented.  That removes the four ways
§3.3.5 says a hand-written filterbank goes wrong -- HTK vs Slaney mel formula,
linear-in-mel spacing of the 66 edges, absence of area normalisation, and the
zeroed DC row -- because none of them is expressed in C at all.

Every spectrum bin feeds at most two adjacent mel bands, so the 257 x 64 matrix
(65,792 bytes dense) collapses to two weight arrays plus a first-band index:
2,313 bytes, and a branch-free two-multiply-accumulate inner loop.
"""

from __future__ import annotations

from pathlib import Path

import numpy as np

ROOT = Path(__file__).resolve().parent.parent
SPECTRUM_BINS = 257
MEL_BANDS = 64


def _literal(value: float) -> str:
    """A float32 literal that round-trips exactly.

    Nine significant decimal digits are enough to recover any float32 (IEEE
    754), and the ``f`` suffix keeps the constant single precision instead of
    promoting the expression to double.
    """

    text = f"{value:.9g}"
    if not any(c in text for c in ".en"):
        text += ".0"
    return text + "f"


def main() -> int:
    matrix = np.load(ROOT / "golden" / "golden.npz")["mel_matrix"]
    assert matrix.shape == (SPECTRUM_BINS, MEL_BANDS), matrix.shape
    assert matrix.dtype == np.float32, matrix.dtype

    first_band = np.zeros(SPECTRUM_BINS, dtype=np.uint8)
    weight0 = np.zeros(SPECTRUM_BINS, dtype=np.float32)
    weight1 = np.zeros(SPECTRUM_BINS, dtype=np.float32)

    for row in range(SPECTRUM_BINS):
        bands = np.nonzero(matrix[row])[0]
        if bands.size == 0:
            continue
        # The compact form can only describe up to two adjacent bands.  A
        # different mel configuration would break that, so fail loudly here
        # rather than silently dropping weights.
        assert bands.size <= 2, (row, bands)
        assert bands[-1] - bands[0] + 1 == bands.size, (row, bands)
        first_band[row] = bands[0]
        weight0[row] = matrix[row, bands[0]]
        if bands.size == 2:
            weight1[row] = matrix[row, bands[0] + 1]
        assert bands[0] + bands.size <= MEL_BANDS, (row, bands)

    nonzero = int(np.count_nonzero(matrix))
    lines = [
        "/****************************************************************"
        "**********//**",
        " * @file     numl_yamnet_tables.h",
        " * @brief    Mel filterbank exported from"
        " tf.signal.linear_to_mel_weight_matrix.",
        " *",
        " * GENERATED by tools/make_tables.py -- do not edit by hand.",
        " *",
        f" * 64 mel bands, {SPECTRUM_BINS} spectrum bins, 125..7500 Hz,"
        " 16 kHz sample rate.",
        f" * {nonzero} non-zero weights; every bin feeds at most two adjacent"
        " bands, so",
        " * bin k contributes w0 to band b[k] and w1 to band b[k]+1.",
        " * Bins below 125 Hz (including DC) and above 7500 Hz carry zero"
        " weight.",
        " ****************************************************************"
        "**************/",
        "#ifndef NUML_YAMNET_TABLES_H",
        "#define NUML_YAMNET_TABLES_H",
        "",
        "#include <stdint.h>",
        "",
        f"#define NUML_YAMNET_MEL_NONZERO {nonzero}",
        "",
        "static const uint8_t g_au8MelFirstBand[NUML_YAMNET_SPECTRUM_BINS] =",
        "{",
    ]

    def _rows(values, render, per_line):
        out = []
        for start in range(0, len(values), per_line):
            chunk = values[start:start + per_line]
            out.append("    " + " ".join(render(v) + "," for v in chunk))
        return out

    lines += _rows(first_band, lambda v: f"{int(v):3d}", 16)
    lines += ["};", "", "static const float g_afMelWeight0[NUML_YAMNET_SPECTRUM_BINS] =", "{"]
    lines += _rows(weight0, lambda v: f"{_literal(float(v)):>14s}", 6)
    lines += ["};", "", "static const float g_afMelWeight1[NUML_YAMNET_SPECTRUM_BINS] =", "{"]
    lines += _rows(weight1, lambda v: f"{_literal(float(v)):>14s}", 6)
    lines += ["};"]

    # --- FFT twiddles -------------------------------------------------
    # Computed in double and rounded once to float32.  Deriving them at
    # runtime from a float32 "pi/step" instead loses several digits in the
    # angle, which shows up as a raised noise floor: for a pure tone the quiet
    # bins are then dominated by FFT rounding rather than by real leakage, and
    # ln(mel + 0.001) amplifies that into millivolts of log error.
    fft_n = 512
    j = np.arange(fft_n // 2, dtype=np.float64)
    angle = -2.0 * np.pi * j / float(fft_n)
    twiddle_re = np.cos(angle).astype(np.float32)
    twiddle_im = np.sin(angle).astype(np.float32)

    lines += [
        "",
        "/* W[j] = exp(-2*pi*i*j/512), j < 256.  A radix-2 stage of half-width",
        " * `step` uses W[k * (256 / step)] for its k-th butterfly. */",
        f"#define NUML_YAMNET_TWIDDLE_COUNT {fft_n // 2}",
        "",
        "static const float g_afTwiddleRe[NUML_YAMNET_TWIDDLE_COUNT] =",
        "{",
    ]
    lines += _rows(twiddle_re, lambda v: f"{_literal(float(v)):>14s}", 6)
    lines += ["};", "", "static const float g_afTwiddleIm[NUML_YAMNET_TWIDDLE_COUNT] =", "{"]
    lines += _rows(twiddle_im, lambda v: f"{_literal(float(v)):>14s}", 6)
    lines += ["};"]

    lines += ["", "#endif /* NUML_YAMNET_TABLES_H */", ""]

    out = ROOT / "frontend" / "numl_yamnet_tables.h"
    out.write_text("\n".join(lines), encoding="utf-8")
    print(f"wrote {out} ({out.stat().st_size:,} bytes)")
    print(f"non-zero weights {nonzero}; table bytes "
          f"{SPECTRUM_BINS * (1 + 4 + 4):,} vs dense {matrix.size * 4:,}")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
