"""Vendor the App Builder Known Sound pack into mcu_toolkit/apps/known_sound/ (GCC edition).

Run by the maintainer through ``vendor_mcu_toolkit.py known-sound``; students never run it.

Two kinds of output:

* the verified C -- ``frontend/`` (the portable YAMNet 96x64 log-mel the host tests compile
  bit-for-bit against TensorFlow) and ``device/`` (DMIC + LPPDMA capture, and the one
  ``BoardConfig.h`` that decides which microphone pins exist on which board) -- copied byte for
  byte, because the point of that code is that the desktop and the board run the same
  translation unit;
* ``main.cpp.in``, a *static* token template built once from the App Builder's
  ``known_sound_runtime._MAIN_TEMPLATE`` so the Studio needs neither jinja2 nor the App Builder
  at deploy time.

Every App Builder placeholder that the Studio does not fill in at deploy time is resolved here:
``tm_local.mcu.codegen.render_tokens`` refuses a template carrying any leftover ``@@TOKEN@@``, so
the only ones allowed to survive are the seven in :data:`DEPLOY_TOKENS`.

The one behavioural change from upstream is the threshold. The App Builder compiles a single
``KNOWN_SOUND_THRESHOLD`` for every class; ``known_sound`` is multi-label, each class carries its
own independent sigmoid score, and the Studio lets the student tune one threshold per class -- so
the scalar becomes ``s_afThreshold[]`` and the single pre-computed output code becomes one code
per class. Every anchor below is checked ``count == 1``: a silently skipped edit would ship
firmware that looks right and thresholds the wrong classes.
"""
from __future__ import annotations

import json
import re
import shutil
import sys
from pathlib import Path
from types import ModuleType

PROJECT_ROOT = Path(__file__).resolve().parents[1]
if str(PROJECT_ROOT) not in sys.path:
    sys.path.insert(0, str(PROJECT_ROOT))

APP_BUILDER_VERSION = "0.1.8"
EXPECTED_RUNTIME_MARKER = "NUML_APP_BUILDER_KNOWN_SOUND_RUNTIME_V0_1_8"

FRONTEND = (
    "numl_yamnet_frontend.c",
    "numl_yamnet_frontend.h",
    "numl_yamnet_tables.h",
    "numl_known_sound.c",
    "numl_known_sound.h",
)
DEVICE = ("numl_dmic.c", "numl_dmic.h", "BoardConfig.h")
#: Only the harness is vendored from the App Builder's ``tests/``.  Its ``test_frontend.py`` and
#: ``test_postprocess.py`` resolve ``ROOT/model/conversion_report.json`` and the App Builder's own
#: project layout, neither of which exists here, so a vendored copy could never run -- dead code
#: shipped to students.  Their assertions live in the Studio's own
#: ``tests/test_known_sound_frontend_host.py``, which drives this harness directly.
HOST_TEST_FILES = ("harness.py",)
#: ``make_golden.py`` and ``make_scores.py`` are deliberately NOT vendored: both hard-code the
#: maintainer's ``.venv`` and a private training project, and both need TensorFlow plus a model
#: that is not in this repository, so nobody downstream could re-run them anyway.  The vectors
#: they produced (``golden/``) are what the Studio checks against.  ``make_tables.py`` stays --
#: it regenerates ``numl_yamnet_tables.h`` from the exported matrix and carries no such paths.
HOST_TOOL_FILES = ("make_tables.py",)
#: ``golden/wav/`` holds the six source recordings the golden vectors were produced from
#: (192 KiB).  Nothing in this repository reads them -- the Studio's host test compares against
#: the already-extracted vectors in ``golden.npz`` / ``scores.npz`` -- so they are not vendored.
GOLDEN_EXCLUDE_DIRS = ("wav",)

#: Key paths whose *values* are absolute paths on the maintainer's machine.  Redacted rather than
#: deleted: the surrounding keys record how the golden vectors were produced, and the host tests
#: read scale / zero_point / case lists out of the very same files.
META_REDACTIONS: dict[str, tuple[tuple[str, ...], ...]] = {
    "golden_meta.json": (("real_clips", "project"),),
    "scores_meta.json": (("model",),),
}
REDACTED = "<redacted>"

#: A vendored text file carrying one of these is a privacy leak, not a build problem: the pack
#: ships to students inside the Studio zip.
PRIVATE_PATH_RE = re.compile(rb"[A-Za-z]:[\\/]{1,2}Users[\\/]{1,2}|/Users/|\.venv", re.IGNORECASE)
TEXT_SUFFIXES = frozenset({".py", ".json", ".md", ".c", ".h", ".in", ".txt"})

#: The only tokens allowed to survive vendoring; Task 4 renders these per project.
DEPLOY_TOKENS = (
    "@@ARENA@@",
    "@@CLASS_COUNT@@",
    "@@CLIP_SAMPLES@@",
    "@@HOP_SAMPLES@@",
    "@@HOLD_HOPS@@",
    "@@LABELS@@",
    "@@THRESHOLDS@@",
)

HEADER = (
    "/* Generated by scripts/vendor_known_sound.py from NuML App Builder v0.1.8 "
    "known_sound_runtime._MAIN_TEMPLATE; per-class thresholds added for Teachable Machine "
    "Local Studio. */\n"
)

#: Declared, not included: the Studio writes Model.cpp itself (tm_local/mcu/codegen.py
#: ``model_cpp_text``), which defines these two in ``arm::app::nn``. Same wording the image
#: templates already carry, so both kinds bind to one model-data contract.
#:
#: ``const`` matters: Nuvoton's upstream wording is ``extern uint8_t *GetModelPointer();`` while
#: the definition the Studio generates returns ``const uint8_t *`` (the model table lives in
#: flash, so it has to). Two declarations of one function with different return types is an ODR
#: violation no compiler is required to diagnose -- it happens to work on this ABI -- so both
#: sides say ``const``. ``Model::Init()`` takes ``const uint8_t* nnModelAddr``, so the call site
#: below needs no cast.
MODEL_DECLS = (
    "namespace nn {\n"
    "extern const uint8_t *GetModelPointer();\n"
    "extern size_t GetModelLen();\n"
    "}\n"
)

LABELS_BLOCK = "static const char *const s_apszLabels[KNOWN_SOUND_CLASSES] =\n{\n@@LABELS@@\n};\n"
THRESHOLD_ARRAY = (
    "\n"
    "/* One independent sigmoid threshold per class (Studio class_thresholds). */\n"
    "static const float s_afThreshold[KNOWN_SOUND_CLASSES] =\n"
    "{\n"
    "@@THRESHOLDS@@\n"
    "};\n"
)

THRESHOLD_CODE_OLD = (
    "    const int iThresholdCode = NuML_KnownSound_ThresholdCode(\n"
    "        KNOWN_SOUND_THRESHOLD, psOutput->params.scale, psOutput->params.zero_point);\n"
)
THRESHOLD_CODE_NEW = (
    "    int aiThresholdCode[KNOWN_SOUND_CLASSES];\n"
    "\n"
    "    for (int i = 0; i < KNOWN_SOUND_CLASSES; i++)\n"
    "    {\n"
    "        aiThresholdCode[i] = NuML_KnownSound_ThresholdCode(\n"
    "            s_afThreshold[i], psOutput->params.scale, psOutput->params.zero_point);\n"
    "    }\n"
)

THRESHOLD_PRINT_OLD = (
    '    printf("INFO detection threshold %.2f -> output code >= %d\\n",\n'
    "           (double)KNOWN_SOUND_THRESHOLD, iThresholdCode);\n"
)
THRESHOLD_PRINT_NEW = (
    "    for (int i = 0; i < KNOWN_SOUND_CLASSES; i++)\n"
    "    {\n"
    '        printf("INFO threshold[%s] %.2f -> output code >= %d\\n",\n'
    "               s_apszLabels[i], (double)s_afThreshold[i], aiThresholdCode[i]);\n"
    "    }\n"
)

#: ``host_tests/harness.py`` is the one vendored host file the Studio rewrites, and both edits
#: exist because the App Builder's copy assumes it owns its own tree:
#:
#: * it builds into ``<pack>/build_host/``, writing ``build.bat`` and a DLL beside the vendored
#:   sources. ``mcu_toolkit/`` is hashed file-for-file by ``manifest.json`` (and forbids ``.bat``),
#:   so that turns a passing frontend check into a failing vendoring check. The build now goes to
#:   a caller-chosen ``build_dir``, defaulting to the git-ignored ``workspace/tmp/mcu_host``.
#: * it hard-codes one vcvars64.bat path and raises when it is absent. Studio machines are not
#:   required to carry MSVC, so discovery becomes ``find_vcvars() -> Path | None`` (TM_VCVARS64,
#:   then vswhere, then the App Builder's fixed path) and the caller skips on None.
#:
#: The rebuild decision moves from mtime to the sha256 of the C sources, recorded next to the DLL:
#: a fresh checkout or a re-vendor rewrites every timestamp but changes no content.
HARNESS_PATHS_OLD = r'''import ctypes
import subprocess
from pathlib import Path

ROOT = Path(__file__).resolve().parent.parent
FRONTEND = ROOT / "frontend"
BUILD = ROOT / "build_host"
'''
HARNESS_PATHS_NEW = r'''import ctypes
import hashlib
import json
import os
import shutil
import subprocess
from pathlib import Path

ROOT = Path(__file__).resolve().parent.parent
FRONTEND = ROOT / "frontend"
# Never inside mcu_toolkit/: that tree is hashed file-for-file by manifest.json and must carry
# no .bat and no build output.  workspace/tmp/ is git-ignored.
DEFAULT_BUILD_DIR = Path("workspace") / "tmp" / "mcu_host"
'''

HARNESS_STAMP_OLD = r'''_cached: ctypes.CDLL | None = None
_cached_stamp: tuple[tuple[str, int], ...] | None = None


def _stamp() -> tuple[tuple[str, int], ...]:
    return tuple(
        (p.name, p.stat().st_mtime_ns) for p in sorted(FRONTEND.glob("*.[ch]"))
    )
'''
HARNESS_STAMP_NEW = r'''_CREATE_NO_WINDOW = getattr(subprocess, "CREATE_NO_WINDOW", 0)

_cached: ctypes.CDLL | None = None
_cached_stamp: tuple[str, tuple[tuple[str, str], ...]] | None = None


def find_vcvars() -> Path | None:
    """Locate vcvars64.bat, or None when this machine has no MSVC C compiler.

    Order: the TM_VCVARS64 override, then whatever vswhere.exe reports for the newest install
    that actually carries the x64 C toolset, then the App Builder's own fixed path.  The caller
    is expected to skip -- not fail -- on None: a student machine need not have a C compiler.
    """
    override = os.environ.get("TM_VCVARS64")
    if override and Path(override).is_file():
        return Path(override)
    for root_var in ("ProgramFiles(x86)", "ProgramFiles"):
        root = os.environ.get(root_var)
        if not root:
            continue
        vswhere = Path(root) / "Microsoft Visual Studio" / "Installer" / "vswhere.exe"
        if not vswhere.is_file():
            continue
        try:
            result = subprocess.run(
                [
                    str(vswhere),
                    "-latest",
                    "-products",
                    "*",
                    "-requires",
                    "Microsoft.VisualStudio.Component.VC.Tools.x86.x64",
                    "-property",
                    "installationPath",
                ],
                capture_output=True,
                text=True,
                timeout=30,
                creationflags=_CREATE_NO_WINDOW,
            )
        except (OSError, subprocess.SubprocessError):
            continue
        for line in result.stdout.splitlines():
            install = line.strip()
            if not install:
                continue
            candidate = Path(install) / "VC" / "Auxiliary" / "Build" / "vcvars64.bat"
            if candidate.is_file():
                return candidate
    return _VCVARS if _VCVARS.is_file() else None


def _stamp() -> tuple[tuple[str, str], ...]:
    """Rebuild on content, not mtime: a checkout or a re-vendor rewrites every timestamp."""
    return tuple(
        (p.name, hashlib.sha256(p.read_bytes()).hexdigest())
        for p in sorted(FRONTEND.glob("*.[ch]"))
    )


def _stamp_file(build_dir: Path) -> Path:
    return build_dir / "numl_frontend.stamp.json"


def _read_stamp(build_dir: Path) -> tuple[tuple[str, str], ...] | None:
    try:
        raw = json.loads(_stamp_file(build_dir).read_text(encoding="utf-8"))
        return tuple((str(name), str(digest)) for name, digest in raw)
    except (OSError, ValueError, TypeError):
        return None
'''

HARNESS_BUILD_OLD = r'''def _compile() -> Path:
    sources = sorted(FRONTEND.glob("*.c"))
    if not sources:
        raise FileNotFoundError(f"No C sources in {FRONTEND}")
    if not _VCVARS.is_file():
        raise FileNotFoundError(f"MSVC environment script not found: {_VCVARS}")

    BUILD.mkdir(parents=True, exist_ok=True)
    dll = BUILD / "numl_frontend.dll"
    names = " ".join(f'"{path}"' for path in sources)

    # A batch file sidesteps the quoting rules that apply when a path
    # containing spaces is passed through "cmd.exe /c" on the command line.
    # /fp:precise stops the compiler reassociating float arithmetic, which
    # would silently change results relative to the target build.
    script = BUILD / "build.bat"
    script.write_text(
        "@echo off\n"
        f'call "{_VCVARS}" >nul\n'
        # No trailing backslash inside a quoted argument: cmd reads the
        # \" as an escaped quote and swallows the rest of the line.  The
        # batch runs with BUILD as its working directory, so bare output
        # names suffice.
        f'cl /nologo /LD /O2 /fp:precise /W3 /WX /Fe:{dll.name} {names}'
        f' /link /INCREMENTAL:NO\n',
        encoding="utf-8",
    )
    result = subprocess.run(
        ["cmd.exe", "/c", str(script)],
        capture_output=True,
        text=True,
        cwd=str(BUILD),
    )
    if result.returncode != 0 or not dll.is_file():
        raise RuntimeError(
            "Host build of the frontend failed:\n"
            + (result.stdout or "")
            + (result.stderr or "")
        )
    return dll


def frontend() -> ctypes.CDLL:
    """Build (if needed) and return the loaded frontend library."""

    global _cached, _cached_stamp
    stamp = _stamp()
    if _cached is not None and _cached_stamp == stamp:
        return _cached
    _cached = ctypes.CDLL(str(_compile()))
    _cached_stamp = stamp
    return _cached
'''
HARNESS_BUILD_NEW = r'''def _msvc_environment(vcvars: Path) -> dict[str, str]:
    """The environment vcvars64.bat exports, so cl.exe can be launched directly afterwards.

    Upstream generated a batch script instead, to sidestep the quoting rules that apply when a
    path containing spaces goes through "cmd.exe /c".  The Studio cannot: tests/test_distribution
    asserts the whole tree holds exactly two student batch files (01_INSTALL, 02_START), and a
    generated third one fails that wherever it lands -- workspace/ included.  Only the vcvars
    path crosses cmd here, as its own argv entry, and the compiler itself never does.
    """
    result = subprocess.run(
        ["cmd.exe", "/c", "call", str(vcvars), "&&", "set"],
        capture_output=True,
        text=True,
        timeout=300,
        creationflags=_CREATE_NO_WINDOW,
    )
    if result.returncode != 0:
        raise RuntimeError(
            f"{vcvars} failed:\n" + (result.stdout or "") + (result.stderr or "")
        )
    env = dict(os.environ)
    for line in result.stdout.splitlines():
        name, sep, value = line.partition("=")
        if sep and name and " " not in name:
            env[name] = value
    return env


def _compile(build_dir: Path) -> Path:
    sources = sorted(FRONTEND.glob("*.c"))
    if not sources:
        raise FileNotFoundError(f"No C sources in {FRONTEND}")
    vcvars = find_vcvars()
    if vcvars is None:
        raise FileNotFoundError(
            "MSVC environment script (vcvars64.bat) not found; set TM_VCVARS64 or install "
            "the Visual Studio Build Tools C++ workload"
        )

    build_dir.mkdir(parents=True, exist_ok=True)
    dll = build_dir / "numl_frontend.dll"
    env = _msvc_environment(vcvars)
    # CreateProcess resolves a bare name against the *parent* PATH, which has no cl.exe, so the
    # compiler is resolved against the PATH vcvars just produced and then launched by full path.
    compiler = shutil.which("cl.exe", path=env.get("PATH", ""))
    if compiler is None:
        raise RuntimeError(f"{vcvars} ran but left no cl.exe on PATH")

    # /fp:precise stops the compiler reassociating float arithmetic, which
    # would silently change results relative to the target build.  Outputs are bare names
    # because the build runs with build_dir as its working directory.
    result = subprocess.run(
        [
            compiler,
            "/nologo",
            "/LD",
            "/O2",
            "/fp:precise",
            "/W3",
            "/WX",
            f"/Fe:{dll.name}",
            *[str(path) for path in sources],
            "/link",
            "/INCREMENTAL:NO",
        ],
        capture_output=True,
        text=True,
        cwd=str(build_dir),
        env=env,
        timeout=600,
        creationflags=_CREATE_NO_WINDOW,
    )
    if result.returncode != 0 or not dll.is_file():
        raise RuntimeError(
            "Host build of the frontend failed:\n"
            + (result.stdout or "")
            + (result.stderr or "")
        )
    _stamp_file(build_dir).write_text(
        json.dumps([list(entry) for entry in _stamp()], indent=2), encoding="utf-8"
    )
    return dll


def frontend(build_dir: Path | None = None) -> ctypes.CDLL:
    """Build (if needed) and return the loaded frontend library.

    ``build_dir`` defaults to the git-ignored ``workspace/tmp/mcu_host`` below the current
    working directory.  The DLL is reused across processes while the sha256 of the C sources
    recorded beside it still matches, and rebuilt the moment any of them changes.
    """

    global _cached, _cached_stamp
    target = (Path(build_dir) if build_dir is not None else DEFAULT_BUILD_DIR).resolve()
    stamp = _stamp()
    key = (str(target), stamp)
    if _cached is not None and _cached_stamp == key:
        return _cached
    dll = target / "numl_frontend.dll"
    if not (dll.is_file() and _read_stamp(target) == stamp):
        dll = _compile(target)
    _cached = ctypes.CDLL(str(dll))
    _cached_stamp = key
    return _cached
'''

HARNESS_PATCHES = (
    ("harness paths", HARNESS_PATHS_OLD, HARNESS_PATHS_NEW),
    ("harness stamp and vcvars discovery", HARNESS_STAMP_OLD, HARNESS_STAMP_NEW),
    ("harness build and load", HARNESS_BUILD_OLD, HARNESS_BUILD_NEW),
)

README = (
    "Known Sound device runtime vendored from NuML App Builder v0.1.8 (Apache-2.0) by\n"
    "`scripts/vendor_mcu_toolkit.py known-sound`; never edit by hand.\n\n"
    "frontend/: portable YAMNet 96x64 log-mel C (bit-checked against TensorFlow by host_tests/).\n"
    "device/: DMIC + LPPDMA capture and per-board BoardConfig.h.\n"
    "host_tests/: the App Builder's build harness plus the golden vectors the Studio's own\n"
    "tests/test_known_sound_frontend_host.py compares against; it builds the frontend with\n"
    "MSVC, so those checks are skipped where MSVC is absent. The App Builder's own test\n"
    "modules and the source .wav recordings are not vendored: nothing here can run or read\n"
    "them.\n"
    "harness.py is the one host file this script patches (see HARNESS_PATCHES): the build goes\n"
    "to workspace/tmp/mcu_host/ instead of into this tree, and find_vcvars() returns None rather\n"
    "than raising when MSVC is absent. tests/test_known_sound_frontend_host.py drives it.\n"
    "main.cpp.in: token template rendered at deploy time (per-class thresholds).\n\n"
    "Tokens: " + " ".join(DEPLOY_TOKENS) + "\n"
    "Board is chosen by a compile-time define -- BOARD_NUMAKER_X_M55M1D or\n"
    "BOARD_NUGESTUREAI_M55M1 -- which is what selects the DMIC pins and channel in\n"
    "BoardConfig.h; on the GestureAI board BoardConfig.h also pulls in numl_cdc.h/numl_usbd.h,\n"
    "so apps/common/cdc/cdc_only must be on the include path there.\n"
)


def _fail(message: str) -> None:
    raise SystemExit(f"vendor_known_sound: {message}")


def _replace_once(text: str, old: str, new: str, label: str) -> str:
    found = text.count(old)
    if found != 1:
        _fail(f"known_sound template anchor {label!r} found {found} times")
    return text.replace(old, new)


def _import_known_sound_runtime(app_builder_root: Path) -> ModuleType:
    """Import the App Builder runtime module without writing into its (read-only) tree."""
    module_path = app_builder_root / "tools" / "known_sound_runtime.py"
    if not module_path.is_file():
        _fail(f"App Builder Known Sound runtime not found at {module_path}")
    if str(app_builder_root) not in sys.path:
        sys.path.insert(0, str(app_builder_root))
    previous = sys.dont_write_bytecode
    sys.dont_write_bytecode = True
    try:
        from tools import known_sound_runtime  # App Builder module (read-only use)
    finally:
        sys.dont_write_bytecode = previous
    marker = getattr(known_sound_runtime, "KNOWN_SOUND_RUNTIME_MARKER", "")
    if marker != EXPECTED_RUNTIME_MARKER:
        _fail(
            f"App Builder runtime marker is {marker!r}, expected {EXPECTED_RUNTIME_MARKER!r}; "
            f"this pack claims App Builder v{APP_BUILDER_VERSION} -- re-check the anchors below "
            "before bumping it"
        )
    return known_sound_runtime


def build_main_template(runtime: ModuleType) -> str:
    """Turn ``_MAIN_TEMPLATE`` into the Studio's static, seven-token ``main.cpp.in``."""
    text = runtime._MAIN_TEMPLATE
    text = _replace_once(
        text, "@@MARKER@@", "TEACHABLE_MACHINE_LOCAL_STUDIO_KNOWN_SOUND_RUNTIME_V1", "marker"
    )
    text = _replace_once(text, "@@MODEL_SOURCE_INCLUDES@@", "", "includes")
    text = _replace_once(text, "@@MODEL_SOURCE_DECLS@@", MODEL_DECLS, "decls")
    text = _replace_once(text, "@@MODEL_SOURCE_LOADER@@", "", "loader")
    # Internal flash only: the Studio never deploys a model from the SD card, so the SD loader
    # and its FatFs includes must not reach the vendored template at all.
    text = _replace_once(text, "@@MODEL_INIT@@", runtime._MODEL_INIT_INTERNAL, "init")
    text = _replace_once(
        text, "@@MODEL_SIZE_EXPR@@", "(unsigned)arm::app::nn::GetModelLen()", "size"
    )

    # One threshold per class instead of one for the whole model.
    text = _replace_once(
        text, "#define KNOWN_SOUND_THRESHOLD    @@THRESHOLD@@f\n", "", "threshold define"
    )
    text = _replace_once(text, LABELS_BLOCK, LABELS_BLOCK + THRESHOLD_ARRAY, "labels")
    text = _replace_once(text, THRESHOLD_CODE_OLD, THRESHOLD_CODE_NEW, "threshold code")
    text = _replace_once(text, THRESHOLD_PRINT_OLD, THRESHOLD_PRINT_NEW, "threshold print")
    text = _replace_once(
        text,
        '(psOutput->data.int8[i] >= iThresholdCode) ? "*" : " "',
        '(psOutput->data.int8[i] >= aiThresholdCode[i]) ? "*" : " "',
        "marker star",
    )

    # Round half to EVEN, not half away from zero. TFLite's own quantiser, the Studio's
    # Preview runner and the host golden all use half-even (numpy's rint / C's lrintf under
    # the default FE_TONEAREST); lroundf rounds .5 away from zero, so every log-mel value
    # landing exactly on a half-code came out one LSB higher on the board than in the golden
    # the host tests compare against.
    text = _replace_once(
        text,
        "int iCode = (int)lroundf(s_afPatch[i] / fInScale) + iInZero;",
        "int iCode = (int)lrintf(s_afPatch[i] / fInScale) + iInZero;",
        "patch quantisation rounding",
    )

    for token in DEPLOY_TOKENS:
        if token not in text:
            _fail(f"token {token} missing after transformation")
    for forbidden in ("@@THRESHOLD@@", "@@MODEL_", "KNOWN_SOUND_THRESHOLD", "lroundf"):
        if forbidden in text:
            _fail(f"{forbidden} still present after transformation")
    # The const-correct declaration must be the only one: a second, non-const declaration
    # anywhere in the file would put the ODR violation straight back.
    if text.count("extern const uint8_t *GetModelPointer();") != 1:
        _fail("expected exactly one const-qualified GetModelPointer() declaration")
    if re.search(r"extern\s+uint8_t\s*\*\s*GetModelPointer", text):
        _fail("a non-const GetModelPointer() declaration survived vendoring")
    # \b before `i` does not match inside `aiThresholdCode`, so this finds a surviving use of the
    # single shared threshold code without tripping over the per-class array that replaced it.
    if re.search(r"\biThresholdCode\b", text):
        _fail("the single shared iThresholdCode still has a use after transformation")
    # render_tokens() raises on ANY leftover token, so the surviving set must be exactly the seven
    # the deploy step knows how to fill in -- no more, and (checked above) no fewer.
    survivors = set(re.findall(r"@@[A-Z0-9_]+@@", text))
    if survivors != set(DEPLOY_TOKENS):
        _fail(f"unexpected tokens survived vendoring: {sorted(survivors - set(DEPLOY_TOKENS))}")
    return HEADER + text


def patch_harness(text: str) -> str:
    """Redirect the host build out of the vendored tree and make MSVC optional.

    Same discipline as the main.cpp.in anchors above: every replacement must hit exactly once,
    and the result is re-checked for the constructs the patches exist to remove.  A silently
    skipped edit here would put a generated build script and a DLL back inside ``mcu_toolkit/``,
    where the manifest test would blame the vendoring rather than this script.
    """
    for label, old, new in HARNESS_PATCHES:
        text = _replace_once(text, old, new, label)
    for required in ("def find_vcvars(", "def frontend(build_dir", "def _msvc_environment(",
                     "hashlib.sha256", "DEFAULT_BUILD_DIR", "TM_VCVARS64"):
        if required not in text:
            _fail(f"harness.py lacks {required!r} after patching")
    # "build.bat" and the write that produced it: the repository ships exactly two .bat files and
    # tests/test_distribution.py scans the whole tree, so a generated third one fails it wherever
    # it lands -- including under the git-ignored workspace/tmp/.
    for forbidden in ("build_host", "st_mtime_ns", "BUILD.mkdir", "cwd=str(BUILD)", "build.bat"):
        if forbidden in text:
            _fail(f"harness.py still contains {forbidden!r} after patching")
    return text


def redact_meta(path: Path, key_paths: tuple[tuple[str, ...], ...]) -> None:
    """Replace absolute maintainer paths inside a vendored ``*_meta.json`` with ``<redacted>``.

    The value is swapped in the raw text rather than by re-serialising the parsed document, and
    newlines are read and written untranslated, so every other byte of the App Builder's file
    survives: a reviewer diffing the vendored tree sees one changed value and nothing else.
    """
    raw = path.read_text(encoding="utf-8", newline="")
    data = json.loads(raw)
    for key_path in key_paths:
        node = data
        for key in key_path[:-1]:
            node = node.get(key) if isinstance(node, dict) else None
            if not isinstance(node, dict):
                _fail(f"{path.name}: no object at {'/'.join(key_path)}; upstream layout changed")
        value = node.get(key_path[-1])
        if not isinstance(value, str):
            _fail(f"{path.name}: {'/'.join(key_path)} is not a string; upstream layout changed")
        encoded = json.dumps(value)
        if raw.count(encoded) != 1:
            _fail(f"{path.name}: {'/'.join(key_path)} value found {raw.count(encoded)} times")
        raw = raw.replace(encoded, json.dumps(REDACTED))
    path.write_text(raw, encoding="utf-8", newline="")


def verify_no_private_paths(out: Path) -> None:
    """Fail the vendoring rather than ship a home directory inside the student zip."""
    for path in sorted(out.rglob("*")):
        if path.is_file() and path.suffix.lower() in TEXT_SUFFIXES:
            found = PRIVATE_PATH_RE.search(path.read_bytes())
            if found:
                _fail(f"{path} carries a developer path: {found.group().decode('latin-1')!r}")


def _patch_harness_file(path: Path) -> None:
    """Rewrite the copied harness in place, keeping the upstream file's line endings."""
    raw = path.read_bytes()
    newline = "\r\n" if b"\r\n" in raw else "\n"
    text = raw.decode("utf-8").replace("\r\n", "\n")
    path.write_text(patch_harness(text), encoding="utf-8", newline=newline)


def vendor_known_sound(app_builder_root: Path, dest_root: Path) -> None:
    known_sound_runtime = _import_known_sound_runtime(app_builder_root)
    main_text = build_main_template(known_sound_runtime)

    pack_src = app_builder_root / "known_sound"
    if not pack_src.is_dir():
        _fail(f"App Builder Known Sound pack not found at {pack_src}")

    out = dest_root / "apps" / "known_sound"
    if out.exists():
        shutil.rmtree(out)
    (out / "frontend").mkdir(parents=True)
    (out / "device").mkdir()
    for name in FRONTEND:
        shutil.copy2(pack_src / "frontend" / name, out / "frontend" / name)
    for name in DEVICE:
        shutil.copy2(pack_src / "device" / name, out / "device" / name)

    # Copied, not run, by this script: tests/test_known_sound_frontend_host.py drives the golden
    # vectors from the Studio's own suite, importing only harness.py.  The App Builder's own two
    # test modules are deliberately left behind (see HOST_TEST_FILES).
    host = out / "host_tests"
    host.mkdir()
    shutil.copytree(
        pack_src / "golden", host / "golden", ignore=shutil.ignore_patterns(*GOLDEN_EXCLUDE_DIRS)
    )
    for name, key_paths in META_REDACTIONS.items():
        redact_meta(host / "golden" / name, key_paths)
    for name in HOST_TEST_FILES:
        shutil.copy2(pack_src / "tests" / name, host / name)
    _patch_harness_file(host / "harness.py")
    for name in HOST_TOOL_FILES:
        source = pack_src / "tools" / name
        if source.is_file():
            shutil.copy2(source, host / name)

    (out / "main.cpp.in").write_text(main_text, encoding="utf-8", newline="\n")
    (out / "README.md").write_text(README, encoding="utf-8", newline="\n")
    verify_no_private_paths(out)
    print(f"[OK] known_sound: wrote {out / 'main.cpp.in'}")
