"""Render + patch NuML's imgclass main.cpp once per board into mcu_toolkit/apps/image/<board>/.

Run by the maintainer through ``vendor_mcu_toolkit.py image-templates``; students never run it.

The result of this script is a static ``main.cpp.in`` carrying a single ``@@ARENA@@`` token, so
the Studio runtime (``tm_local/mcu/apps/image.py``) needs neither jinja2 nor the App Builder to
produce a project -- it only substitutes the Vela arena size.

Pipeline per board (all inputs read from the *vendored* tree so the output is reproducible from
this repository alone; the upstream NuML checkout is only used to prove it is in sync):

1. copy the vendored ``imgclass_template/NN_ImgClassInference`` into a temporary staging project;
2. render NuML's ``imgclass_codegen/main_cpp_tmpl.jinja2`` over its ``main.cpp``;
3. apply the App Builder's fixed-memory image-classification runtime patch;
4. on the LCD-less board, fold the USB CDC function into the UVC device (main.cpp plus the
   template's own ``Device/UVC/{descriptors.c,UVC.c}``, which are written back into the vendored
   template because they are board files, not generated ones);
5. replace the model-input ROI with a centre crop so the firmware sees the same framing the
   Studio trained on;
6. const-qualify the ``GetModelPointer()`` declaration so it matches the definition the Studio
   generates (see ``MODEL_PTR_OLD``);
7. tokenise the arena size and write ``mcu_toolkit/apps/image/<board>/main.cpp.in``.

Every anchor is checked: a missing or ambiguous one raises ``SystemExit`` naming the anchor,
because a silently skipped patch would ship firmware that looks fine and misbehaves on the board.
"""
from __future__ import annotations

import shutil
import sys
import tempfile
from collections.abc import Callable
from pathlib import Path

PROJECT_ROOT = Path(__file__).resolve().parents[1]
if str(PROJECT_ROOT) not in sys.path:
    sys.path.insert(0, str(PROJECT_ROOT))

BOARDS = ("NuMaker-M55M1", "NuGestureAI-M55M1")
LCD_BOARD = "NuMaker-M55M1"
ARENA_TOKEN = "__ARENA_TOKEN__"
HEADER = (
    "/* Generated by scripts/vendor_image_templates.py from NuML imgclass template + "
    "App Builder preflight; tokens: @@ARENA@@ */\n"
)

# The model-input ROI: the whole (4:3) frame is squashed into the square model input, which does
# not match how the Studio trains (it centre-crops to a square first).
RESIZE_ANCHOR = "resizeImg.w = inputImgCols;"
ROI_OLD = (
    "        roi.x = 0;\n"
    "        roi.y = 0;\n"
    "        roi.w = frameBuffer.w;\n"
    "        roi.h = frameBuffer.h;\n"
)
ROI_NEW = (
    "        roi.x = (frameBuffer.w > frameBuffer.h) ? (frameBuffer.w - frameBuffer.h) / 2 : 0;  "
    "/* centre crop, matches Studio training */\n"
    "        roi.y = (frameBuffer.h > frameBuffer.w) ? (frameBuffer.h - frameBuffer.w) / 2 : 0;\n"
    "        roi.w = (frameBuffer.w < frameBuffer.h) ? frameBuffer.w : frameBuffer.h;\n"
    "        roi.h = roi.w;\n"
)
ROI_WINDOW_LINES = 10

# NuML declares the model-data accessor without the const the Studio's own definition carries
# (`tm_local/mcu/codegen.py::model_cpp_text` returns `const uint8_t *` -- the table lives in
# flash). Two declarations of one function with different return types is an ODR violation no
# compiler has to diagnose, so both sides say `const`. `Model::Init()` takes
# `const uint8_t* nnModelAddr`, so the `arm::app::nn::GetModelPointer()` call site needs no cast.
MODEL_PTR_OLD = "extern uint8_t *GetModelPointer();"
MODEL_PTR_NEW = "extern const uint8_t *GetModelPointer();"

# Markers that prove each patch actually landed. The App Builder patchers return
# ``(changed, backed_up, notes)`` -- `changed` is False both when a patch failed to apply and
# when the file was already patched (re-running this script), so success is judged on content.
PREFLIGHT_MARKERS = (
    "NuML_FindTop1",
    "char predictLabelInfo[160]",
    "static const ARM_MPU_Region_t mpuConfig[]",
    "//#define __LOAD_MODEL_FROM_SD__",
)
CDC_MAIN_MARKERS = ('#include "numl_cdc.h"', "NuML_Overlay_DrawText565", "NuML_CDC_Pump();")
CDC_DESCRIPTOR_MARKERS = ("0x9A, 0x01,",)  # wTotalLength 344 + 66 CDC bytes
CDC_UVC_MARKERS = ("NuML_CDC_ClassRequest", "NuML_CDC_Reset();", "NuML_CDC_HandleBulkIn();")


def _fail(message: str) -> None:
    raise SystemExit(f"vendor_image_templates: {message}")


def _import_app_builder_tools(app_builder_root: Path):
    """Import the App Builder's two patch modules without writing into its (read-only) tree."""
    tools_dir = app_builder_root / "tools"
    if not (tools_dir / "runtime_preflight.py").is_file():
        _fail(f"App Builder tools not found at {tools_dir}")
    if str(app_builder_root) not in sys.path:
        sys.path.insert(0, str(app_builder_root))
    previous = sys.dont_write_bytecode
    sys.dont_write_bytecode = True
    try:
        from tools import runtime_preflight, usb_cdc_runtime  # App Builder modules (read-only use)
    finally:
        sys.dont_write_bytecode = previous
    return runtime_preflight, usb_cdc_runtime


def _render_numl_main(numl_dir: Path, out: Path) -> None:
    from jinja2 import Environment, FileSystemLoader

    tmpl_dir = numl_dir / "imgclass_codegen"
    if not (tmpl_dir / "main_cpp_tmpl.jinja2").is_file():
        _fail(f"NuML main.cpp template not found at {tmpl_dir / 'main_cpp_tmpl.jinja2'}")
    env = Environment(loader=FileSystemLoader(str(tmpl_dir)), trim_blocks=True, lstrip_blocks=True)
    text = env.get_template("main_cpp_tmpl.jinja2").render(
        define_SD_model_load="//#define __LOAD_MODEL_FROM_SD__",
        define_activation_buf_size=f"#define ACTIVATION_BUF_SZ ({ARENA_TOKEN})",
    )
    if ARENA_TOKEN not in text:
        _fail("rendered main.cpp lost the arena token; NuML's template changed")
    out.write_text(text, encoding="utf-8", newline="\n")


def _apply(
    label: str,
    path: Path,
    markers: tuple[str, ...],
    patch: Callable[..., object],
    *args: object,
    **kwargs: object,
) -> None:
    """Run one App Builder patch and prove it landed by its content markers.

    The patchers return ``(changed, backed_up, notes)`` and raise ``RuntimeError`` naming the
    anchor they could not find, so the tuple says nothing about success -- the markers do.
    """
    try:
        patch(*args, **kwargs)
    except RuntimeError as exc:
        _fail(f"{label}: {exc}")
    text = path.read_text(encoding="utf-8")
    for marker in markers:
        if marker not in text:
            _fail(f"{label}: patch left {path.name} without the marker {marker!r}")


def _centre_crop(main: Path) -> None:
    """Replace the model-input ROI (the one just above ``resizeImg.w``) with a centre crop."""
    text = main.read_text(encoding="utf-8")
    if text.count(RESIZE_ANCHOR) != 1:
        _fail(f"{main.name}: expected 1 {RESIZE_ANCHOR!r}, found {text.count(RESIZE_ANCHOR)}")
    line_start = text.rfind("\n", 0, text.index(RESIZE_ANCHOR)) + 1
    window_start = line_start
    for _ in range(ROI_WINDOW_LINES):
        if window_start == 0:
            break
        window_start = text.rfind("\n", 0, window_start - 1) + 1
    window = text[window_start:line_start]
    found = window.count(ROI_OLD)
    if found != 1:
        _fail(
            f"{main.name}: expected exactly one model-input ROI block in the "
            f"{ROI_WINDOW_LINES} lines before {RESIZE_ANCHOR!r}, found {found}"
        )
    text = text[:window_start] + window.replace(ROI_OLD, ROI_NEW) + text[line_start:]
    main.write_text(text, encoding="utf-8", newline="\n")


def _const_model_pointer(main: Path) -> None:
    """Make the model-data declaration agree with the definition the Studio generates."""
    text = main.read_text(encoding="utf-8")
    found = text.count(MODEL_PTR_OLD)
    if found != 1:
        _fail(f"{main.name}: expected 1 {MODEL_PTR_OLD!r}, found {found}")
    main.write_text(text.replace(MODEL_PTR_OLD, MODEL_PTR_NEW), encoding="utf-8", newline="\n")


def _check_upstream_in_sync(numl_root: Path, vendored: Path) -> None:
    """The vendored jinja2 template is the input; fail loudly if upstream has moved on.

    ``--numl-root`` is accepted both as the NuML_Toolkit checkout and as its NuML_TFLM_Tool
    subdirectory, because the `toolkit` subcommand takes the former and this one is usually
    pointed straight at the latter.
    """
    rel = Path("imgclass_codegen") / "main_cpp_tmpl.jinja2"
    for candidate in (numl_root / rel, numl_root / "NuML_TFLM_Tool" / rel):
        if candidate.is_file():
            upstream = candidate
            break
    else:
        print(f"[warn] upstream NuML template not found under {numl_root}; using the vendored copy")
        return
    if upstream.read_bytes() != vendored.read_bytes():
        _fail(
            f"vendored {vendored} differs from upstream {upstream}; "
            "re-run the `toolkit` subcommand before `image-templates`"
        )


def vendor_image_templates(numl_root: Path, app_builder_root: Path, dest_root: Path) -> None:
    runtime_preflight, usb_cdc_runtime = _import_app_builder_tools(app_builder_root)

    from tm_local.mcu import codegen

    numl_dir = dest_root / "NuML_TFLM_Tool"
    _check_upstream_in_sync(numl_root, numl_dir / "imgclass_codegen" / "main_cpp_tmpl.jinja2")
    out_root = dest_root / "apps" / "image"
    if out_root.exists():
        shutil.rmtree(out_root)

    for board in BOARDS:
        template_proj = (
            numl_dir / "templates" / "M55M1" / board / "imgclass_template" / "NN_ImgClassInference"
        )
        if not template_proj.is_dir():
            _fail(f"{board}: vendored imgclass template not found at {template_proj}")
        with tempfile.TemporaryDirectory() as tmp:
            staging = Path(tmp) / "NN_ImgClassInference"
            shutil.copytree(template_proj, staging)
            main = staging / "main.cpp"
            _render_numl_main(numl_dir, main)
            # The preflight reads Labels.hpp/Labels.cpp from a real project; give it the same
            # pair the Studio generates so it patches against the shipping label API.
            codegen.write_labels(["0", "1"], staging / "Model")

            display = (
                runtime_preflight.DISPLAY_OUTPUT_LCD
                if board == LCD_BOARD
                else runtime_preflight.DISPLAY_OUTPUT_UVC
            )
            _apply(
                f"{board}: runtime_preflight._patch_main_cpp",
                main,
                PREFLIGHT_MARKERS,
                runtime_preflight._patch_main_cpp,
                main,
                model_storage=runtime_preflight.IMAGE_STORAGE_INTERNAL_FLASH,
                display_output=display,
            )

            if board != LCD_BOARD:
                uvc_dir = staging / "Device" / "UVC"
                _apply(
                    f"{board}: usb_cdc_runtime._patch_main_cpp",
                    main,
                    CDC_MAIN_MARKERS,
                    usb_cdc_runtime._patch_main_cpp,
                    main,
                    True,
                )
                _apply(
                    f"{board}: usb_cdc_runtime._patch_descriptors",
                    uvc_dir / "descriptors.c",
                    CDC_DESCRIPTOR_MARKERS,
                    usb_cdc_runtime._patch_descriptors,
                    uvc_dir / "descriptors.c",
                )
                _apply(
                    f"{board}: usb_cdc_runtime._patch_uvc_source",
                    uvc_dir / "UVC.c",
                    CDC_UVC_MARKERS,
                    usb_cdc_runtime._patch_uvc_source,
                    uvc_dir / "UVC.c",
                )
                for name in ("descriptors.c", "UVC.c"):
                    shutil.copy2(uvc_dir / name, template_proj / "Device" / "UVC" / name)

            _centre_crop(main)
            _const_model_pointer(main)
            text = HEADER + main.read_text(encoding="utf-8").replace(ARENA_TOKEN, "@@ARENA@@")

        if MODEL_PTR_OLD in text:
            _fail(f"{board}: a non-const GetModelPointer() declaration survived")
        required = [*PREFLIGHT_MARKERS, "@@ARENA@@", "centre crop, matches Studio training",
                    MODEL_PTR_NEW]
        required += list(CDC_MAIN_MARKERS) if board != LCD_BOARD else ["//#define __USE_UVC__"]
        for marker in required:
            if marker not in text:
                _fail(f"{board}: marker missing after patching: {marker}")
        if board == LCD_BOARD and "numl_cdc" in text:
            _fail(f"{board}: LCD board must not carry the USB CDC runtime")
        if text.count("#define ACTIVATION_BUF_SZ") != 1:
            _fail(f"{board}: main.cpp must define ACTIVATION_BUF_SZ exactly once")

        out_dir = out_root / board
        out_dir.mkdir(parents=True, exist_ok=True)
        (out_dir / "main.cpp.in").write_text(text, encoding="utf-8", newline="\n")
        print(f"[OK] {board}: wrote {out_dir / 'main.cpp.in'}")

    (out_root / "README.md").write_text(
        "Image-classification main.cpp templates, one per board.\n\n"
        "Rendered from NuML_TFLM_Tool/imgclass_codegen/main_cpp_tmpl.jinja2 and patched by the\n"
        "NuML App Builder v0.1.8 runtime_preflight / usb_cdc_runtime helpers, then centre-cropped\n"
        "to match Studio training. Regenerate with\n"
        "`scripts/vendor_mcu_toolkit.py image-templates`; never edit by hand.\n\n"
        "Token: @@ARENA@@ -- the Vela tensor arena size in bytes.\n",
        encoding="utf-8",
    )
